export const n2 = {
  遭う: {
    reading: "あう",
    meaning: "to meet,to encounter (undesirable nuance)",
  },
  扇ぐ: { reading: "あおぐ", meaning: "to fan,to flap" },
  青白い: { reading: "あおじろい", meaning: "pale,pallid" },
  明き: { reading: "あき", meaning: "room,time to spare,emptiness" },
  飽くまで: {
    reading: "あくまで",
    meaning: "to the end,to the last,stubbornly",
  },
  明け方: { reading: "あけがた", meaning: "dawn" },
  揚げる: { reading: "あげる", meaning: "to lift,to fry" },
  挙げる: { reading: "あげる", meaning: "to raise,to fly" },
  憧れる: {
    reading: "あこがれる",
    meaning: "to long for,to yearn after,to admire",
  },
  足跡: { reading: "あしあと", meaning: "footprints" },
  味わう: { reading: "あじわう", meaning: "to taste,to savor,to relish" },
  預かる: {
    reading: "あずかる",
    meaning: "to keep in custody,to receive on deposit,to take charge of",
  },
  暖まる: { reading: "あたたまる", meaning: "to warm up,to get warm" },
  暖める: { reading: "あたためる", meaning: "to warm,to heat" },
  厚かましい: { reading: "あつかましい", meaning: "impudent,shameless,brazen" },
  圧縮: { reading: "あっしゅく", meaning: "compression,condensation,pressure" },
  宛名: { reading: "あてな", meaning: "address,direction" },
  暴れる: {
    reading: "あばれる",
    meaning: "to act violently,to rage,to struggle,to be riotous",
  },
  脂: { reading: "あぶら", meaning: "fat,tallow,lard" },
  雨戸: { reading: "あまど", meaning: "sliding storm door" },
  甘やかす: { reading: "あまやかす", meaning: "to pamper,to spoil" },
  余る: {
    reading: "あまる",
    meaning: "to remain,to be left over,to be in excess,to be too many",
  },
  編物: { reading: "あみもの", meaning: "knitting,web" },
  編む: { reading: "あむ", meaning: "to knit" },
  危うい: { reading: "あやうい", meaning: "dangerous,critical,grave" },
  怪しい: { reading: "あやしい", meaning: "suspicious,dubious,doubtful" },
  荒い: { reading: "あらい", meaning: "rough,rude,wild" },
  粗い: { reading: "あらい", meaning: "coarse,rough" },
  争う: {
    reading: "あらそう",
    meaning: "to dispute,to argue,to be at variance,to compete",
  },
  改めて: {
    reading: "あらためて",
    meaning: "another time,again,over again,anew,formally",
  },
  改める: {
    reading: "あらためる",
    meaning: "to change,to alter,to reform,to revise",
  },
  著す: { reading: "あらわす", meaning: "to write,to publish" },
  有難い: {
    reading: "ありがたい",
    meaning: "grateful,thankful,welcome,appreciated,evoking gratitude",
  },
  在る: { reading: "ある", meaning: "to live,to be" },
  安易: { reading: "あんい", meaning: "easy-going" },
  案外: { reading: "あんがい", meaning: "unexpectedly" },
  言い出す: {
    reading: "いいだす",
    meaning:
      "to start talking,to speak,to tell,to propose,to suggest,to break the ice",
  },
  言い付ける: {
    reading: "いいつける",
    meaning: "to tell,to tell on (someone),to order",
  },
  意義: { reading: "いぎ", meaning: "meaning,significance" },
  生き生き: { reading: "いきいき", meaning: "vividly,lively" },
  育児: { reading: "いくじ", meaning: "childcare,nursing,upbringing" },
  幾分: { reading: "いくぶん", meaning: "somewhat" },
  生け花: { reading: "いけばな", meaning: "(1) flower arrangement" },
  以後: {
    reading: "いご",
    meaning: "after this,from now on,hereafter,thereafter",
  },
  以降: { reading: "いこう", meaning: "on and after,hereafter,thereafter" },
  勇ましい: {
    reading: "いさましい",
    meaning: "brave,valiant,gallant,courageous",
  },
  衣食住: {
    reading: "いしょくじゅう",
    meaning: "necessities of life (food, clothing, etc.)",
  },
  意地悪: { reading: "いじわる", meaning: "malicious,ill-tempered,unkind" },
  一応: {
    reading: "いちおう",
    meaning: "once,tentatively,in outline,for the time being",
  },
  一段と: { reading: "いちだんと", meaning: "greater,more,further,still more" },
  一流: {
    reading: "いちりゅう",
    meaning: "first class,top grade,foremost,top-notch",
  },
  佚: {
    reading: "いつ",
    meaning: "be lost,peace,hide,mistake,beautiful,in turn",
  },
  一昨日: { reading: "いっさくじつ", meaning: "day before yesterday" },
  一昨年: { reading: "いっさくねん", meaning: "year before last" },
  一斉: { reading: "いっせい", meaning: "simultaneous,all at once" },
  一旦: {
    reading: "いったん",
    meaning: "once,for a moment,one morning,temporarily",
  },
  一定: { reading: "いってい", meaning: "fixed,settled,definite" },
  移転: { reading: "いてん", meaning: "moving,transfer,demise" },
  井戸: { reading: "いど", meaning: "water well" },
  緯度: { reading: "いど", meaning: "latitude (nav.)" },
  従姉妹: { reading: "いとこ", meaning: "cousin (female)" },
  威張る: { reading: "いばる", meaning: "to be proud,to swagger" },
  嫌がる: { reading: "いやがる", meaning: "to hate,to dislike" },
  煎る: { reading: "いる", meaning: "to parch,to fry" },
  入れ物: { reading: "いれもの", meaning: "container,case,receptacle" },
  引力: { reading: "いんりょく", meaning: "gravity" },
  植木: { reading: "うえき", meaning: "garden shrubs,trees,potted plant" },
  飢える: { reading: "うえる", meaning: "to starve" },
  浮ぶ: {
    reading: "うかぶ",
    meaning: "to float,to rise to surface,to come to mind",
  },
  浮かべる: {
    reading: "うかべる",
    meaning: "to float,to express,to look (sad, glad)",
  },
  浮く: {
    reading: "うく",
    meaning: "to float,to become merry,to become loose",
  },
  承る: {
    reading: "うけたまわる",
    meaning: "(hum) to hear,to be told,to know",
  },
  受取: { reading: "うけとり", meaning: "receipt" },
  受け持つ: { reading: "うけもつ", meaning: "to take (be in) charge of" },
  薄暗い: { reading: "うすぐらい", meaning: "dim,gloomy" },
  薄める: { reading: "うすめる", meaning: "to dilute,to water down" },
  打合せ: {
    reading: "うちあわせ",
    meaning: "business meeting,previous arrangement,appointment",
  },
  打ち消す: { reading: "うちけす", meaning: "to deny,to negate,to contradict" },
  討つ: { reading: "うつ", meaning: "to attack,to avenge" },
  映す: {
    reading: "うつす",
    meaning: "to project,to reflect,to cast (shadow)",
  },
  写る: { reading: "うつる", meaning: "to be photographed,to be projected" },
  映る: {
    reading: "うつる",
    meaning: "to be reflected,to harmonize with,to come out (photo)",
  },
  有無: {
    reading: "うむ",
    meaning:
      "yes or no,existence,flag indicator (comp),presence or absence marker",
  },
  埋める: {
    reading: "うめる",
    meaning: "to bury,to fill up,to fill (a seat, a vacant position)",
  },
  敬う: { reading: "うやまう", meaning: "to show respect,to honour" },
  裏返す: {
    reading: "うらがえす",
    meaning: "to turn inside out,to turn (something) over",
  },
  裏口: { reading: "うらぐち", meaning: "backdoor,rear entrance" },
  占う: { reading: "うらなう", meaning: "to forecast,to predict" },
  恨み: { reading: "うらみ", meaning: "resentment" },
  恨む: { reading: "うらむ", meaning: "to curse,to feel bitter" },
  羨ましい: { reading: "うらやましい", meaning: "envious,enviable" },
  羨む: { reading: "うらやむ", meaning: "to envy" },
  売上: { reading: "うりあげ", meaning: "amount sold,proceeds" },
  売り切れ: { reading: "うりきれ", meaning: "sold-out" },
  売り切れる: { reading: "うりきれる", meaning: "to be sold out" },
  売行き: { reading: "うれゆき", meaning: "sales" },
  運河: { reading: "うんが", meaning: "canal,waterway" },
  英文: { reading: "えいぶん", meaning: "sentence in English" },
  英和: { reading: "えいわ", meaning: "English-Japanese (e.g. dictionary)" },
  液体: { reading: "えきたい", meaning: "liquid,fluid" },
  絵の具: { reading: "えのぐ", meaning: "colors,paints" },
  偉い: {
    reading: "えらい",
    meaning:
      "great,celebrated,eminent,terrible,awful,famous,remarkable,excellent",
  },
  宴会: { reading: "えんかい", meaning: "party,banquet" },
  園芸: { reading: "えんげい", meaning: "horticulture,gardening" },
  演劇: { reading: "えんげき", meaning: "play (theatrical)" },
  円周: { reading: "えんしゅう", meaning: "circumference" },
  遠足: { reading: "えんそく", meaning: "trip,hike,picnic" },
  延長: {
    reading: "えんちょう",
    meaning: "extension,elongation,prolongation,lengthening",
  },
  煙突: { reading: "えんとつ", meaning: "chimney" },
  追い掛ける: {
    reading: "おいかける",
    meaning: "to chase or run after someone,to run down,to pursue",
  },
  追い越す: {
    reading: "おいこす",
    meaning: "to pass (e.g. car),to outdistance,to outstrip",
  },
  応援: { reading: "おうえん", meaning: "aid,assistance,help,reinforcement" },
  王女: { reading: "おうじょ", meaning: "princess" },
  応ずる: {
    reading: "おうずる",
    meaning: "to answer,to respond,to meet,to satisfy,to accept",
  },
  応接: { reading: "おうせつ", meaning: "reception" },
  応対: { reading: "おうたい", meaning: "receiving,dealing with" },
  往復: {
    reading: "おうふく",
    meaning: "(col) round trip,coming and going,return ticket",
  },
  欧米: { reading: "おうべい", meaning: "Europe and America,the West" },
  応用: { reading: "おうよう", meaning: "application,put to practical use" },
  大通り: { reading: "おおどおり", meaning: "main street" },
  大凡: {
    reading: "おおよそ",
    meaning: "about,roughly,as a rule,approximately",
  },
  お帰り: { reading: "おかえり", meaning: "return,welcome" },
  拝む: {
    reading: "おがむ",
    meaning: "to worship,to beg,to make a supplication",
  },
  お代わり: { reading: "おかわり", meaning: "second helping,another cup" },
  補う: { reading: "おぎなう", meaning: "to compensate for" },
  屋外: { reading: "おくがい", meaning: "outdoors" },
  送り仮名: { reading: "おくりがな", meaning: "part of word written in kana" },
  怠る: {
    reading: "おこたる",
    meaning: "to neglect,to be off guard,to be feeling better",
  },
  押える: {
    reading: "おさえる",
    meaning:
      "to stop,to restrain,to seize,to repress,to suppress,to press down",
  },
  納める: {
    reading: "おさめる",
    meaning: "to obtain,to reap,to pay,to supply,to accept",
  },
  治める: {
    reading: "おさめる",
    meaning: "(1) to govern,to manage,(2) to subdue",
  },
  惜しい: { reading: "おしい", meaning: "regrettable,disappointing,precious" },
  御辞儀: { reading: "おじぎ", meaning: "bow" },
  伯父さん: { reading: "おじさん", meaning: "middle-aged gentleman,uncle" },
  小父さん: { reading: "おじさん", meaning: "middle-aged gentleman,uncle" },
  叔父さん: { reading: "おじさん", meaning: "middle-aged gentleman,uncle" },
  教わる: { reading: "おそわる", meaning: "to be taught" },
  落着く: { reading: "おちつく", meaning: "to calm down,to settle down" },
  御手洗: {
    reading: "おてあらい",
    meaning: "font of purifying water placed at entrance of shrine",
  },
  お手伝いさん: { reading: "おてつだいさん", meaning: "maid" },
  落し物: { reading: "おとしもの", meaning: "lost property" },
  驚かす: {
    reading: "おどろかす",
    meaning: "to surprise,to frighten,to create a stir",
  },
  各々: {
    reading: "おのおの",
    meaning: "each,every,either,respectively,severally",
  },
  伯母さん: { reading: "おばさん", meaning: "(hon) aunt" },
  叔母さん: { reading: "おばさん", meaning: "(1) aunt,(2) middle-aged lady" },
  お参り: { reading: "おまいり", meaning: "worship,shrine visit" },
  思い掛けない: { reading: "おもいがけない", meaning: "unexpected,casual" },
  思い込む: {
    reading: "おもいこむ",
    meaning: "to be under impression that,to be convinced that",
  },
  思い付く: { reading: "おもいつく", meaning: "to think of,to hit upon" },
  重たい: { reading: "おもたい", meaning: "heavy,massive,serious" },
  親指: { reading: "おやゆび", meaning: "thumb" },
  卸す: { reading: "おろす", meaning: "to sell wholesale,grated (vegetables)" },
  恩恵: { reading: "おんけい", meaning: "grace,favor,blessing,benefit" },
  温室: { reading: "おんしつ", meaning: "greenhouse" },
  温泉: { reading: "おんせん", meaning: "spa,hot spring,onsen" },
  温帯: { reading: "おんたい", meaning: "temperate zone" },
  御中: { reading: "おんちゅう", meaning: "and Company,Messrs." },
  女の人: { reading: "おんなのひと", meaning: "woman" },
  蚊: { reading: "か", meaning: "mosquito" },
  貝: { reading: "かい", meaning: "shell,shellfish" },
  開会: { reading: "かいかい", meaning: "opening of a meeting" },
  会館: { reading: "かいかん", meaning: "meeting hall,assembly hall" },
  改札: { reading: "かいさつ", meaning: "examination of tickets" },
  解散: { reading: "かいさん", meaning: "breakup,dissolution" },
  海水浴: { reading: "かいすいよく", meaning: "sea bathing,seawater bath" },
  回数: { reading: "かいすう", meaning: "number of times,frequency" },
  回数券: { reading: "かいすうけん", meaning: "book of tickets" },
  改正: { reading: "かいせい", meaning: "revision,amendment,alteration" },
  快晴: { reading: "かいせい", meaning: "good weather" },
  解説: { reading: "かいせつ", meaning: "explanation,commentary" },
  改造: { reading: "かいぞう", meaning: "(1) remodeling,(2) modding (comp)" },
  開通: { reading: "かいつう", meaning: "opening,open" },
  回転: { reading: "かいてん", meaning: "rotation,revolution,turning" },
  解答: { reading: "かいとう", meaning: "answer,solution" },
  回答: { reading: "かいとう", meaning: "reply,answer" },
  外部: { reading: "がいぶ", meaning: "the outside,external" },
  解放: { reading: "かいほう", meaning: "release,liberation,emancipation" },
  開放: { reading: "かいほう", meaning: "open,throw open,liberalization" },
  海洋: { reading: "かいよう", meaning: "ocean" },
  概論: { reading: "がいろん", meaning: "intro,outline,general remarks" },
  帰す: { reading: "かえす", meaning: "to send back" },
  却って: {
    reading: "かえって",
    meaning: "on the contrary,rather,all the more,instead",
  },
  代える: {
    reading: "かえる",
    meaning: "to exchange,to interchange,to substitute,to replace",
  },
  反る: { reading: "かえる", meaning: "to warp,to be warped,to curve" },
  家屋: { reading: "かおく", meaning: "house,building" },
  係わる: {
    reading: "かかわる",
    meaning:
      "to concern oneself in,to have to do with,to affect,to influence,to stick to (opinions)",
  },
  書留: {
    reading: "かきとめ",
    meaning:
      "writing down,putting on record,recording,making a note of,registration (of mail)",
  },
  書取: { reading: "かきとり", meaning: "dictation" },
  垣根: { reading: "かきね", meaning: "hedge" },
  掻く: { reading: "かく", meaning: "to scratch,to perspire" },
  嗅ぐ: { reading: "かぐ", meaning: "to sniff,to smell" },
  架空: { reading: "かくう", meaning: "aerial,overhead,fiction,fanciful" },
  各自: { reading: "かくじ", meaning: "individual,each" },
  拡充: { reading: "かくじゅう", meaning: "expansion" },
  学術: { reading: "がくじゅつ", meaning: "science,learning,scholarship" },
  各地: { reading: "かくち", meaning: "every place,various places" },
  拡張: {
    reading: "かくちょう",
    meaning: "expansion,extension,enlargement,escape (ESC)",
  },
  角度: { reading: "かくど", meaning: "angle" },
  学年: { reading: "がくねん", meaning: "year in school,grade in school" },
  学部: {
    reading: "がくぶ",
    meaning: "department of a university,undergraduate",
  },
  格別: { reading: "かくべつ", meaning: "exceptional" },
  確率: { reading: "かくりつ", meaning: "probability" },
  学力: {
    reading: "がくりょく",
    meaning: "scholarship,knowledge,literary ability",
  },
  掛け算: { reading: "かけざん", meaning: "multiplication" },
  可決: {
    reading: "かけつ",
    meaning: "approval,adoption (e.g. motion, bill),passage",
  },
  火口: { reading: "かこう", meaning: "a burner,origin of a fire" },
  下降: { reading: "かこう", meaning: "downward,descent,fall,drop,subsidence" },
  重なる: {
    reading: "かさなる",
    meaning: "to be piled up,lie on top of one another,overlap each other",
  },
  重ねる: {
    reading: "かさねる",
    meaning:
      "to pile up,to put something on another,to heap up,to add,to repeat",
  },
  飾り: { reading: "かざり", meaning: "decoration" },
  火山: { reading: "かざん", meaning: "volcano" },
  貸し出し: { reading: "かしだし", meaning: "lending,loaning" },
  過失: { reading: "かしつ", meaning: "error,blunder,accident" },
  果実: { reading: "かじつ", meaning: "fruit,nut,berry." },
  貸間: { reading: "かしま", meaning: "room to let" },
  貸家: { reading: "かしや", meaning: "house for rent" },
  個所: { reading: "かしょ", meaning: "passage,place,point,part" },
  過剰: { reading: "かじょう", meaning: "excess,over-" },
  課税: { reading: "かぜい", meaning: "taxation" },
  下線: { reading: "かせん", meaning: "underline,underscore" },
  加速: { reading: "かそく", meaning: "acceleration" },
  加速度: { reading: "かそくど", meaning: "acceleration" },
  固い: {
    reading: "かたい",
    meaning: "stubborn,firm (not viscous or easily moved)",
  },
  堅い: {
    reading: "かたい",
    meaning: "hard (esp. wood),steadfast,honorable,stuffy writing",
  },
  片仮名: { reading: "かたかな", meaning: "katakana" },
  片付く: {
    reading: "かたづく",
    meaning: "to put in order,to dispose of,to solve",
  },
  塊: { reading: "かたまり", meaning: "lump,mass,clod,cluster" },
  固まる: {
    reading: "かたまる",
    meaning: "to harden,to solidify,to become firm,to become certain",
  },
  片道: { reading: "かたみち", meaning: "one-way (trip)" },
  傾く: { reading: "かたむく", meaning: "to incline toward,to slant,to lurch" },
  片寄る: {
    reading: "かたよる",
    meaning: "to be one-sided,to incline,to be partial",
  },
  学科: { reading: "がっか", meaning: "study subject,course of study" },
  学会: { reading: "がっかい", meaning: "scientific society,academic meeting" },
  楽器: { reading: "がっき", meaning: "musical instrument" },
  学級: { reading: "がっきゅう", meaning: "grade in school" },
  担ぐ: { reading: "かつぐ", meaning: "to shoulder,to carry on shoulder" },
  括弧: { reading: "かっこ", meaning: "parenthesis,brackets" },
  活字: { reading: "かつじ", meaning: "printing type" },
  活躍: { reading: "かつやく", meaning: "activity" },
  活力: { reading: "かつりょく", meaning: "vitality,energy" },
  仮定: { reading: "かてい", meaning: "assumption,supposition,hypothesis" },
  過程: { reading: "かてい", meaning: "process" },
  課程: { reading: "かてい", meaning: "course,curriculum" },
  仮名: { reading: "かな", meaning: "(n) alias,pseudonym,pen name" },
  仮名遣い: {
    reading: "かなづかい",
    meaning: "kana orthography,syllabary spelling",
  },
  鐘: { reading: "かね", meaning: "bell,chime" },
  加熱: { reading: "かねつ", meaning: "heating" },
  兼ねる: {
    reading: "かねる",
    meaning: "to hold (position),to serve,to be unable",
  },
  過半数: { reading: "かはんすう", meaning: "majority" },
  被せる: { reading: "かぶせる", meaning: "to cover (with something)" },
  釜: { reading: "かま", meaning: "iron pot,kettle" },
  紙屑: { reading: "かみくず", meaning: "wastepaper" },
  神様: { reading: "かみさま", meaning: "god" },
  剃刀: { reading: "かみそり", meaning: "razor" },
  貨物: { reading: "かもつ", meaning: "cargo,freight" },
  歌謡: { reading: "かよう", meaning: "song,ballad" },
  殻: { reading: "から", meaning: "shell,husk,hull,chaff" },
  空っぽ: { reading: "からっぽ", meaning: "empty,vacant,hollow" },
  枯れる: {
    reading: "かれる",
    meaning: "to wither,to die (plant),to be blasted (plant)",
  },
  乾かす: {
    reading: "かわかす",
    meaning: "to dry (clothes, etc.),to desiccate",
  },
  渇く: { reading: "かわく", meaning: "to be thirsty" },
  為替: { reading: "かわせ", meaning: "money order,exchange" },
  瓦: { reading: "かわら", meaning: "roof tile" },
  代る: {
    reading: "かわる",
    meaning: "(v5r,vi) to take the place of,to relieve,to be substituted for",
  },
  間隔: { reading: "かんかく", meaning: "space,interval,SPC" },
  換気: { reading: "かんき", meaning: "ventilation" },
  感激: { reading: "かんげき", meaning: "deep emotion,impression,inspiration" },
  鑑賞: { reading: "かんしょう", meaning: "appreciation" },
  感ずる: { reading: "かんずる", meaning: "to feel,to sense" },
  間接: { reading: "かんせつ", meaning: "indirection,indirectness" },
  乾燥: { reading: "かんそう", meaning: "dry,arid,insipid,dehydrated" },
  感想: { reading: "かんそう", meaning: "impressions,thoughts" },
  観測: { reading: "かんそく", meaning: "observation" },
  寒帯: { reading: "かんたい", meaning: "frigid zone" },
  官庁: { reading: "かんちょう", meaning: "government office,authorities" },
  勘違い: { reading: "かんちがい", meaning: "misunderstanding,wrong guess" },
  缶詰: {
    reading: "かんづめ",
    meaning: "packing (in cans),canning,canned goods,tin can",
  },
  乾電池: { reading: "かんでんち", meaning: "dry cell,battery" },
  関東: {
    reading: "かんとう",
    meaning: "eastern half of Japan, including Tokyo",
  },
  観念: {
    reading: "かんねん",
    meaning: "(1) idea,notion,conception,(2) sense (e.g. of duty)",
  },
  乾杯: { reading: "かんぱい", meaning: "toast (drink)" },
  看板: { reading: "かんばん", meaning: "sign,signboard,doorplate,poster" },
  看病: { reading: "かんびょう", meaning: "nursing (a patient)" },
  冠: { reading: "かんむり", meaning: "crown,diadem,first,best" },
  漢和: {
    reading: "かんわ",
    meaning: "Chinese Character-Japanese (e.g. dictionary)",
  },
  気圧: { reading: "きあつ", meaning: "atmospheric pressure" },
  器械: { reading: "きかい", meaning: "instrument" },
  着替え: { reading: "きがえ", meaning: "changing clothes,change of clothes" },
  機関車: { reading: "きかんしゃ", meaning: "locomotive,engine" },
  飢饉: { reading: "ききん", meaning: "famine" },
  器具: { reading: "きぐ", meaning: "utensil" },
  期限: { reading: "きげん", meaning: "term,period" },
  記号: { reading: "きごう", meaning: "symbol,code" },
  刻む: { reading: "きざむ", meaning: "to mince,to carve,to engrave" },
  儀式: { reading: "ぎしき", meaning: "ceremony,rite,ritual,service" },
  基準: { reading: "きじゅん", meaning: "standard,basis,criteria,norm" },
  規準: { reading: "きじゅん", meaning: "standard,basis,criteria,norm" },
  起床: { reading: "きしょう", meaning: "rising,getting out of bed" },
  着せる: { reading: "きせる", meaning: "to put on clothes" },
  基礎: { reading: "きそ", meaning: "foundation,basis" },
  気体: { reading: "きたい", meaning: "vapour,gas" },
  基地: { reading: "きち", meaning: "base" },
  基盤: { reading: "きばん", meaning: "foundation,basis" },
  客席: { reading: "きゃくせき", meaning: "guest seating" },
  客間: { reading: "きゃくま", meaning: "parlor,guest room" },
  休業: {
    reading: "きゅうぎょう",
    meaning: "closed (e.g. store),business suspended,shutdown,holiday",
  },
  休講: { reading: "きゅうこう", meaning: "lecture cancelled" },
  休息: { reading: "きゅうそく", meaning: "rest,relief,relaxation" },
  給与: { reading: "きゅうよ", meaning: "allowance,grant,supply" },
  休養: { reading: "きゅうよう", meaning: "rest,break,recreation" },
  清い: { reading: "きよい", meaning: "clear,pure,noble" },
  強化: {
    reading: "きょうか",
    meaning: "strengthen,intensify,reinforce,solidify",
  },
  境界: { reading: "きょうかい", meaning: "boundary" },
  行事: { reading: "ぎょうじ", meaning: "event,function" },
  恐縮: {
    reading: "きょうしゅく",
    meaning: "shame,very kind of you,sorry to trouble",
  },
  教養: {
    reading: "きょうよう",
    meaning: "culture,education,refinement,cultivation",
  },
  行列: {
    reading: "ぎょうれつ",
    meaning: "(1) line,procession,(2) matrix (math)",
  },
  漁業: { reading: "ぎょぎょう", meaning: "fishing (industry)" },
  曲線: { reading: "きょくせん", meaning: "curve" },
  規律: { reading: "きりつ", meaning: "order,rules,law" },
  斬る: { reading: "きる", meaning: "(v5r) to behead,to murder" },
  気を付ける: {
    reading: "きをつける",
    meaning: "to be careful,to pay attention,to take care",
  },
  金魚: { reading: "きんぎょ", meaning: "goldfish" },
  区域: {
    reading: "くいき",
    meaning: "limits,boundary,domain,zone,sphere,territory",
  },
  偶数: { reading: "ぐうすう", meaning: "even number" },
  空想: { reading: "くうそう", meaning: "daydream,fantasy,fancy,vision" },
  空中: { reading: "くうちゅう", meaning: "sky,air" },
  釘: { reading: "くぎ", meaning: "nail" },
  区切る: {
    reading: "くぎる",
    meaning: "to punctuate,to cut off,to mark off,to stop,to put an end to",
  },
  櫛: { reading: "くし", meaning: "comb" },
  苦情: { reading: "くじょう", meaning: "complaint,troubles,objection" },
  苦心: { reading: "くしん", meaning: "pain,trouble" },
  屑: { reading: "くず", meaning: "waste,scrap" },
  崩す: {
    reading: "くずす",
    meaning: "to destroy,to pull down,to make change (money)",
  },
  薬指: { reading: "くすりゆび", meaning: "ring finger" },
  崩れる: { reading: "くずれる", meaning: "to collapse,to crumble" },
  砕く: { reading: "くだく", meaning: "to break,to smash" },
  砕ける: { reading: "くだける", meaning: "to break,to be broken" },
  下る: { reading: "くだる", meaning: "to get down,to descend" },
  唇: { reading: "くちびる", meaning: "lips" },
  口紅: { reading: "くちべに", meaning: "lipstick" },
  句読点: { reading: "くとうてん", meaning: "punctuation marks" },
  配る: { reading: "くばる", meaning: "to distribute,to deliver" },
  工夫: { reading: "くふう", meaning: "labourer,worker" },
  区分: { reading: "くぶん", meaning: "division,section,classification" },
  組合せ: { reading: "くみあわせ", meaning: "combination" },
  組み立てる: {
    reading: "くみたてる",
    meaning: "to assemble,to set up,to construct",
  },
  汲む: {
    reading: "くむ",
    meaning: "(1) to draw (water),to dip,to scoop,to pump",
  },
  酌む: { reading: "くむ", meaning: "to serve sake" },
  悔しい: { reading: "くやしい", meaning: "regrettable,mortifying,vexing" },
  悔やむ: { reading: "くやむ", meaning: "to mourn" },
  郡: { reading: "ぐん", meaning: "country,district" },
  稽古: { reading: "けいこ", meaning: "practice,training,study" },
  敬語: { reading: "けいご", meaning: "honorific,term of respect" },
  蛍光灯: {
    reading: "けいこうとう",
    meaning: "fluorescent lamp,person who is slow to react",
  },
  形式: {
    reading: "けいしき",
    meaning: "form,formality,format,math expression",
  },
  継続: { reading: "けいぞく", meaning: "continuation" },
  毛糸: { reading: "けいと", meaning: "knitting wool" },
  経度: { reading: "けいど", meaning: "longitude" },
  系統: {
    reading: "けいとう",
    meaning: "system,family line,geological formation",
  },
  芸能: {
    reading: "げいのう",
    meaning: "public entertainment,accomplishments,attainments",
  },
  競馬: { reading: "けいば", meaning: "horse racing" },
  警備: { reading: "けいび", meaning: "defense,guard,policing,security" },
  形容詞: { reading: "けいようし", meaning: "true adjective" },
  形容動詞: {
    reading: "けいようどうし",
    meaning: "adjectival noun,quasi-adjective",
  },
  外科: { reading: "げか", meaning: "surgical department" },
  毛皮: { reading: "けがわ", meaning: "fur,skin,pelt" },
  激増: { reading: "げきぞう", meaning: "sudden increase" },
  下車: { reading: "げしゃ", meaning: "alighting,getting off" },
  下旬: { reading: "げじゅん", meaning: "month (last third of)" },
  下水: { reading: "げすい", meaning: "drainage,sewage,ditch,gutter,sewerage" },
  削る: {
    reading: "けずる",
    meaning: "to cut down little by little,to take a percentage",
  },
  桁: { reading: "けた", meaning: "column,beam,digit" },
  下駄: { reading: "げた", meaning: "geta (Japanese footwear),wooden clogs" },
  血圧: { reading: "けつあつ", meaning: "blood pressure" },
  血液: { reading: "けつえき", meaning: "blood" },
  月給: { reading: "げっきゅう", meaning: "monthly salary" },
  傑作: { reading: "けっさく", meaning: "masterpiece,best work,boner,blunder" },
  月末: { reading: "げつまつ", meaning: "end of the month" },
  気配: { reading: "けはい", meaning: "indication,market trend,worry" },
  下品: {
    reading: "げひん",
    meaning: "vulgarity,meanness,indecency,coarseness",
  },
  煙い: { reading: "けむい", meaning: "smoky" },
  蹴る: { reading: "ける", meaning: "to kick" },
  険しい: { reading: "けわしい", meaning: "inaccessible place,sharp eyes" },
  見学: {
    reading: "けんがく",
    meaning: "inspection,study by observation,field trip",
  },
  謙虚: { reading: "けんきょ", meaning: "modesty,humility" },
  原稿: { reading: "げんこう", meaning: "manuscript,copy" },
  原産: { reading: "げんさん", meaning: "place of origin,habitat" },
  原始: { reading: "げんし", meaning: "origin,primeval" },
  研修: { reading: "けんしゅう", meaning: "training" },
  厳重: { reading: "げんじゅう", meaning: "strict,rigour,severe,firm" },
  謙遜: { reading: "けんそん", meaning: "humble,humility,modesty" },
  県庁: { reading: "けんちょう", meaning: "prefectural office" },
  限度: { reading: "げんど", meaning: "limit,bounds" },
  現に: { reading: "げんに", meaning: "actually,really" },
  顕微鏡: { reading: "けんびきょう", meaning: "microscope" },
  原理: { reading: "げんり", meaning: "principle,theory,fundamental truth" },
  原料: { reading: "げんりょう", meaning: "raw materials" },
  碁: { reading: "ご", meaning: "Go (board game of capturing territory)" },
  恋しい: {
    reading: "こいしい",
    meaning: "(1) dear,beloved,darling,(2) yearned for",
  },
  請う: { reading: "こう", meaning: "to ask,to request" },
  工員: { reading: "こういん", meaning: "factory worker" },
  強引: {
    reading: "ごういん",
    meaning: "overbearing,coercive,pushy,forcible,high-handed",
  },
  公害: { reading: "こうがい", meaning: "public nuisance,pollution" },
  高級: { reading: "こうきゅう", meaning: "high class,high grade" },
  公共: {
    reading: "こうきょう",
    meaning: "public,community,public service,society,communal",
  },
  工芸: { reading: "こうげい", meaning: "industrial arts" },
  孝行: { reading: "こうこう", meaning: "filial piety" },
  交差: { reading: "こうさ", meaning: "cross" },
  講師: { reading: "こうし", meaning: "lecturer" },
  工事: { reading: "こうじ", meaning: "construction work" },
  公式: { reading: "こうしき", meaning: "formula,formality,official" },
  口実: { reading: "こうじつ", meaning: "excuse" },
  こうして: { reading: "こうして", meaning: "thus" },
  校舎: { reading: "こうしゃ", meaning: "school building" },
  公衆: { reading: "こうしゅう", meaning: "the public" },
  香水: { reading: "こうすい", meaning: "perfume" },
  公正: { reading: "こうせい", meaning: "justice,fairness,impartiality" },
  功績: {
    reading: "こうせき",
    meaning: "achievements,merit,meritorious service,meritorious deed",
  },
  光線: { reading: "こうせん", meaning: "beam,light ray" },
  高層: { reading: "こうそう", meaning: "upper" },
  構造: { reading: "こうぞう", meaning: "structure,construction" },
  交替: {
    reading: "こうたい",
    meaning: "alternation,change,relief,relay,shift",
  },
  耕地: { reading: "こうち", meaning: "arable land" },
  交通機関: { reading: "こうつうきかん", meaning: "transportation facilities" },
  校庭: { reading: "こうてい", meaning: "campus" },
  肯定: { reading: "こうてい", meaning: "positive,affirmation" },
  高度: { reading: "こうど", meaning: "altitude,height,advanced" },
  高等: { reading: "こうとう", meaning: "high class,high grade" },
  合同: {
    reading: "ごうどう",
    meaning: "combination,incorporation,union,amalgamation",
  },
  後輩: { reading: "こうはい", meaning: "junior (at work or school)" },
  公表: {
    reading: "こうひょう",
    meaning: "official announcement,proclamation",
  },
  鉱物: { reading: "こうぶつ", meaning: "mineral" },
  公務: { reading: "こうむ", meaning: "official business,public business" },
  項目: { reading: "こうもく", meaning: "item" },
  紅葉: { reading: "こうよう", meaning: "(1) (Japanese) maple" },
  合理: { reading: "ごうり", meaning: "rational" },
  交流: {
    reading: "こうりゅう",
    meaning:
      "alternating current,intercourse,(cultural) exchange,intermingling",
  },
  合流: { reading: "ごうりゅう", meaning: "confluence,union,linking up,merge" },
  効力: { reading: "こうりょく", meaning: "effect,efficacy,validity,potency" },
  超える: { reading: "こえる", meaning: "to exceed,to cross over,to cross" },
  焦がす: { reading: "こがす", meaning: "to burn,to scorch,to singe,to char" },
  国王: { reading: "こくおう", meaning: "king" },
  国籍: { reading: "こくせき", meaning: "nationality" },
  国立: { reading: "こくりつ", meaning: "national" },
  焦げる: { reading: "こげる", meaning: "to burn,to be burned" },
  凍える: {
    reading: "こごえる",
    meaning: "to freeze,to be chilled,to be frozen",
  },
  心当たり: {
    reading: "こころあたり",
    meaning: "having some knowledge of,happening to know",
  },
  心得る: {
    reading: "こころえる",
    meaning: "to be informed,to have thorough knowledge",
  },
  腰掛け: { reading: "こしかけ", meaning: "seat,bench" },
  腰掛ける: { reading: "こしかける", meaning: "to sit (down)" },
  五十音: { reading: "ごじゅうおん", meaning: "the Japanese syllabary" },
  胡椒: { reading: "こしょう", meaning: "pepper" },
  超す: { reading: "こす", meaning: "to cross,to pass,to tide over" },
  擦る: {
    reading: "こする",
    meaning: "to rub,to chafe,to file,to frost (glass),to strike (match)",
  },
  個体: { reading: "こたい", meaning: "an individual" },
  御馳走: { reading: "ごちそう", meaning: "feast,treating (someone)" },
  小遣い: {
    reading: "こづかい",
    meaning:
      "personal expenses,pocket money,spending money,incidental expenses,allowance",
  },
  古典: { reading: "こてん", meaning: "old book,classics,classic" },
  琴: { reading: "こと", meaning: "Koto (Japanese harp)" },
  言付ける: {
    reading: "ことづける",
    meaning: "to send word,to send a message",
  },
  言葉遣い: { reading: "ことばづかい", meaning: "speech,expression,wording" },
  御無沙汰: {
    reading: "ごぶさた",
    meaning: "not writing or contacting for a while",
  },
  塵芥: { reading: "ごみ", meaning: "trash,rubbish" },
  御免: {
    reading: "ごめん",
    meaning: "your pardon,declining (something),dismissal,permission",
  },
  小指: { reading: "こゆび", meaning: "little finger" },
  娯楽: { reading: "ごらく", meaning: "pleasure,amusement" },
  御覧: { reading: "ごらん", meaning: "(hon) look,inspection,try" },
  転がす: { reading: "ころがす", meaning: "to roll" },
  転がる: { reading: "ころがる", meaning: "to roll,to tumble" },
  紺: { reading: "こん", meaning: "navy blue,deep blue" },
  混合: { reading: "こんごう", meaning: "mixing,mixture" },
  献立: { reading: "こんだて", meaning: "menu,program,schedule" },
  在学: { reading: "ざいがく", meaning: "(enrolled) in school" },
  再三: { reading: "さいさん", meaning: "again and again,repeatedly" },
  祭日: { reading: "さいじつ", meaning: "national holiday,festival day" },
  催促: {
    reading: "さいそく",
    meaning: "request,demand,claim,urge (action),press for",
  },
  採点: { reading: "さいてん", meaning: "marking,grading,looking over" },
  災難: { reading: "さいなん", meaning: "calamity,misfortune" },
  裁縫: { reading: "さいほう", meaning: "sewing" },
  材木: { reading: "ざいもく", meaning: "lumber,timber" },
  逆さ: { reading: "さかさ", meaning: "reverse,inversion,upside down" },
  逆様: { reading: "さかさま", meaning: "inversion,upside down" },
  捜す: { reading: "さがす", meaning: "to search,to seek,to look for" },
  遡る: {
    reading: "さかのぼる",
    meaning: "to go back,to go upstream,to make retroactive",
  },
  酒場: { reading: "さかば", meaning: "bar,bar-room" },
  先程: { reading: "さきほど", meaning: "some time ago" },
  裂く: { reading: "さく", meaning: "to tear,to split" },
  索引: { reading: "さくいん", meaning: "index,indices" },
  作者: { reading: "さくしゃ", meaning: "author,authoress" },
  削除: {
    reading: "さくじょ",
    meaning: "elimination,cancellation,deletion,erasure",
  },
  作成: { reading: "さくせい", meaning: "frame,draw up,make,producing" },
  作製: { reading: "さくせい", meaning: "manufacture" },
  探る: { reading: "さぐる", meaning: "to search,to look for,to sound out" },
  囁く: { reading: "ささやく", meaning: "to whisper,to murmur" },
  刺さる: { reading: "ささる", meaning: "to stick,to be stuck" },
  匙: { reading: "さじ", meaning: "spoon" },
  座敷: { reading: "ざしき", meaning: "tatami room" },
  差し支え: { reading: "さしつかえ", meaning: "hindrance,impediment" },
  差し引き: {
    reading: "さしひき",
    meaning: "deduction,subtraction,balance,ebb and flow,rise and fall",
  },
  刺身: { reading: "さしみ", meaning: "sliced raw fish" },
  刺す: { reading: "さす", meaning: "to pierce,to stab,to prick,to thrust" },
  挿す: {
    reading: "さす",
    meaning: "to insert,to put in,to graft,to wear in belt",
  },
  注す: { reading: "さす", meaning: "to pour (drink),to serve (drinks)" },
  射す: { reading: "さす", meaning: "to shine,to strike" },
  流石: {
    reading: "さすが",
    meaning: "clever,adept,good,expectations,as one would expect",
  },
  撮影: { reading: "さつえい", meaning: "photographing" },
  雑音: { reading: "ざつおん", meaning: "noise (jarring, grating)" },
  早速: {
    reading: "さっそく",
    meaning: "at once,immediately,without delay,promptly",
  },
  錆: { reading: "さび", meaning: "rust (colour)" },
  錆びる: { reading: "さびる", meaning: "to rust,to become rusty" },
  座布団: { reading: "ざぶとん", meaning: "cushion (Japanese)" },
  冷ます: { reading: "さます", meaning: "to cool,to dampen,to let cool" },
  妨げる: { reading: "さまたげる", meaning: "to disturb,to prevent" },
  冷める: {
    reading: "さめる",
    meaning: "to become cool,to wear off,to abate,to subside",
  },
  再来月: { reading: "さらいげつ", meaning: "month after next" },
  再来週: { reading: "さらいしゅう", meaning: "week after next" },
  再来年: { reading: "さらいねん", meaning: "year after next" },
  騒がしい: { reading: "さわがしい", meaning: "noisy" },
  三角: { reading: "さんかく", meaning: "triangle,triangular" },
  算数: { reading: "さんすう", meaning: "arithmetic" },
  酸性: { reading: "さんせい", meaning: "acidity" },
  産地: { reading: "さんち", meaning: "producing area" },
  山林: {
    reading: "さんりん",
    meaning: "mountain forest,mountains and forest",
  },
  仕上がる: { reading: "しあがる", meaning: "to be finished" },
  寺院: { reading: "じいん", meaning: "temple" },
  しいんと: {
    reading: "（する）",
    meaning: "silent (as the grave),(deathly) quiet",
  },
  自衛: { reading: "じえい", meaning: "self-defense" },
  塩辛い: { reading: "しおからい", meaning: "salty (taste)" },
  司会: { reading: "しかい", meaning: "chairmanship" },
  四角: { reading: "しかく", meaning: "square" },
  四角い: { reading: "しかくい", meaning: "square" },
  時間割: { reading: "じかんわり", meaning: "timetable,schedule" },
  四季: { reading: "しき", meaning: "four seasons" },
  敷地: { reading: "しきち", meaning: "site" },
  至急: { reading: "しきゅう", meaning: "urgent,pressing" },
  敷く: { reading: "しく", meaning: "to spread out,to lay out" },
  茂る: {
    reading: "しげる",
    meaning: "to grow thick,to luxuriate,to be luxurious",
  },
  持参: { reading: "じさん", meaning: "bringing,taking,carrying" },
  磁石: { reading: "じしゃく", meaning: "magnet" },
  四捨五入: { reading: "ししゃごにゅう", meaning: "rounding up (fractions)" },
  始終: { reading: "しじゅう", meaning: "continuously,from beginning to end" },
  自習: { reading: "じしゅう", meaning: "self-study" },
  静まる: {
    reading: "しずまる",
    meaning: "to quieten down,to calm down,to subside",
  },
  姿勢: { reading: "しせい", meaning: "attitude,posture" },
  自然科学: { reading: "しぜんかがく", meaning: "natural science" },
  時速: { reading: "じそく", meaning: "speed (per hour)" },
  子孫: { reading: "しそん", meaning: "descendants,posterity,offspring" },
  死体: { reading: "したい", meaning: "corpse" },
  下書き: { reading: "したがき", meaning: "rough copy,draft" },
  下町: { reading: "したまち", meaning: "Shitamachi,lower parts of town" },
  自治: { reading: "じち", meaning: "self-government,autonomy" },
  実感: { reading: "じっかん", meaning: "feelings (actual, true)" },
  湿気: { reading: "しっけ", meaning: "moisture,humidity,dampness" },
  湿気: { reading: "しっき", meaning: "moisture,humidity,dampness" },
  実習: { reading: "じっしゅう", meaning: "practice,training" },
  実績: { reading: "じっせき", meaning: "achievements,actual results" },
  湿度: { reading: "しつど", meaning: "level of humidity" },
  執筆: { reading: "しっぴつ", meaning: "writing" },
  実物: { reading: "じつぶつ", meaning: "real thing,original" },
  実用: { reading: "じつよう", meaning: "practical use,utility" },
  実力: { reading: "じつりょく", meaning: "merit,efficiency,arms,force" },
  実例: { reading: "じつれい", meaning: "example,illustration" },
  失恋: {
    reading: "しつれん",
    meaning: "disappointed love,broken heart,unrequited love,be lovelorn",
  },
  指定: {
    reading: "してい",
    meaning: "designation,specification,assignment,pointing at",
  },
  私鉄: { reading: "してつ", meaning: "private railway" },
  児童: { reading: "じどう", meaning: "children,juvenile" },
  縛る: { reading: "しばる", meaning: "to tie,to bind" },
  地盤: { reading: "じばん", meaning: "(the) ground" },
  紙幣: { reading: "しへい", meaning: "paper money,notes,bills" },
  絞る: { reading: "しぼる", meaning: "to press,to wring,to squeeze" },
  縞: { reading: "しま", meaning: "stripe" },
  地味: { reading: "じみ", meaning: "plain,simple" },
  氏名: { reading: "しめい", meaning: "full name,identity" },
  締切: {
    reading: "しめきり",
    meaning: "closing,cut-off,end,deadline,Closed,No Entrance",
  },
  締め切る: { reading: "しめきる", meaning: "to shut up" },
  湿る: { reading: "しめる", meaning: "to be wet,to become wet,to be damp" },
  社会科学: { reading: "しゃかいかがく", meaning: "social science" },
  蛇口: { reading: "じゃぐち", meaning: "faucet,tap" },
  弱点: { reading: "じゃくてん", meaning: "weak point,weakness" },
  車庫: { reading: "しゃこ", meaning: "garage,car shed" },
  車掌: { reading: "しゃしょう", meaning: "(train) conductor" },
  写生: { reading: "しゃせい", meaning: "sketching,drawing from nature" },
  社説: { reading: "しゃせつ", meaning: "editorial,leading article" },
  車輪: { reading: "しゃりん", meaning: "(car) wheel" },
  洒落: { reading: "しゃれ", meaning: "joke,pun,witticism" },
  集会: { reading: "しゅうかい", meaning: "meeting,assembly" },
  住居: { reading: "じゅうきょ", meaning: "dwelling,house,residence,address" },
  集金: { reading: "しゅうきん", meaning: "money collection" },
  集合: {
    reading: "しゅうごう",
    meaning: "gathering,assembly,meeting,set (math)",
  },
  習字: { reading: "しゅうじ", meaning: "penmanship" },
  修繕: { reading: "しゅうぜん", meaning: "repair,mending" },
  重体: {
    reading: "じゅうたい",
    meaning: "seriously ill,serious condition,critical state",
  },
  じゅうたん: { reading: "（カーペット）", meaning: "carpet" },
  終点: { reading: "しゅうてん", meaning: "terminus,last stop (e.g train)" },
  重点: {
    reading: "じゅうてん",
    meaning: "important point,lay stress on,colon,emphasis",
  },
  就任: { reading: "しゅうにん", meaning: "inauguration,assumption of office" },
  周辺: {
    reading: "しゅうへん",
    meaning: "circumference,outskirts,environs,(computer) peripheral",
  },
  重役: { reading: "じゅうやく", meaning: "director,high executive" },
  終了: { reading: "しゅうりょう", meaning: "end,close,termination" },
  重量: {
    reading: "じゅうりょう",
    meaning: "(1) weight,(2) heavyweight boxer",
  },
  重力: { reading: "じゅうりょく", meaning: "gravity" },
  熟語: {
    reading: "じゅくご",
    meaning: "idiom,idiomatic phrase,kanji compound",
  },
  祝日: { reading: "しゅくじつ", meaning: "national holiday" },
  縮小: { reading: "しゅくしょう", meaning: "reduction,curtailment" },
  受験: { reading: "じゅけん", meaning: "taking an examination" },
  主語: { reading: "しゅご", meaning: "(gram) subject" },
  出勤: { reading: "しゅっきん", meaning: "going to work,at work" },
  述語: { reading: "じゅつご", meaning: "predicate" },
  出張: { reading: "しゅっちょう", meaning: "official tour,business trip" },
  寿命: { reading: "じゅみょう", meaning: "life span" },
  主役: {
    reading: "しゅやく",
    meaning: "leading part,leading actor (actress)",
  },
  受話器: { reading: "じゅわき", meaning: "(telephone) receiver" },
  循環: { reading: "じゅんかん", meaning: "circulation,rotation,cycle" },
  巡査: { reading: "じゅんさ", meaning: "police,policeman" },
  順々: { reading: "じゅんじゅん", meaning: "in order,in turn" },
  順序: { reading: "じゅんじょ", meaning: "order,sequence,procedure" },
  純情: {
    reading: "じゅんじょう",
    meaning: "pure heart,naivete,self-sacrificing devotion",
  },
  純粋: { reading: "じゅんすい", meaning: "pure,true,genuine,unmixed" },
  消化: { reading: "しょうか", meaning: "digestion" },
  小学生: { reading: "しょうがくせい", meaning: "grade school student" },
  将棋: { reading: "しょうぎ", meaning: "Japanese chess" },
  蒸気: { reading: "じょうき", meaning: "steam,vapour" },
  定規: { reading: "じょうぎ", meaning: "(measuring) ruler" },
  上級: {
    reading: "じょうきゅう",
    meaning: "advanced level,high grade,senior",
  },
  商業: { reading: "しょうぎょう", meaning: "commerce,trade,business" },
  消極的: { reading: "しょうきょくてき", meaning: "passive" },
  賞金: { reading: "しょうきん", meaning: "prize,monetary award" },
  上下: {
    reading: "じょうげ",
    meaning:
      "high and low,up and down,unloading and loading,praising and blaming",
  },
  障子: { reading: "しょうじ", meaning: "paper sliding door" },
  商社: { reading: "しょうしゃ", meaning: "trading company,firm" },
  乗車: { reading: "じょうしゃ", meaning: "taking a train,entraining" },
  上旬: { reading: "じょうじゅん", meaning: "first 10 days of month" },
  生ずる: {
    reading: "しょうずる",
    meaning: "to cause,to arise,to be generated",
  },
  小数: { reading: "しょうすう", meaning: "fraction (part of),decimal" },
  商店: { reading: "しょうてん", meaning: "shop,business firm" },
  焦点: { reading: "しょうてん", meaning: "focus,point" },
  消毒: { reading: "しょうどく", meaning: "disinfection,sterilization" },
  勝敗: {
    reading: "しょうはい",
    meaning: "victory or defeat,issue (of battle)",
  },
  蒸発: {
    reading: "じょうはつ",
    meaning: "evaporation,unexplained disappearance",
  },
  賞品: { reading: "しょうひん", meaning: "prize,trophy" },
  勝負: {
    reading: "しょうぶ",
    meaning: "victory or defeat,match,contest,game,bout",
  },
  小便: { reading: "しょうべん", meaning: "(col) urine,piss" },
  消防署: { reading: "しょうぼうしょ", meaning: "fire station" },
  正味: { reading: "しょうみ", meaning: "net (weight)" },
  正面: { reading: "しょうめん", meaning: "the front,honesty" },
  消耗: { reading: "しょうもう", meaning: "exhaustion,consumption" },
  醤油: { reading: "しょうゆ", meaning: "soy sauce" },
  省略: {
    reading: "しょうりゃく",
    meaning: "omission,abbreviation,abridgment",
  },
  初級: { reading: "しょきゅう", meaning: "elementary level" },
  助教授: { reading: "じょきょうじゅ", meaning: "assistant professor" },
  食塩: { reading: "しょくえん", meaning: "table salt" },
  職人: { reading: "しょくにん", meaning: "worker,mechanic,artisan,craftsman" },
  初旬: { reading: "しょじゅん", meaning: "first 10 days of the month" },
  書籍: { reading: "しょせき", meaning: "book,publication" },
  食器: { reading: "しょっき", meaning: "tableware" },
  書店: { reading: "しょてん", meaning: "bookshop" },
  書道: { reading: "しょどう", meaning: "calligraphy" },
  白髪: {
    reading: "しらが",
    meaning: "white or grey hair,trendy hair bleaching",
  },
  知合い: { reading: "しりあい", meaning: "acquaintance" },
  私立: { reading: "しりつ", meaning: "private (establishment)" },
  資料: { reading: "しりょう", meaning: "materials,data" },
  汁: { reading: "しる", meaning: "juice,sap,soup,broth" },
  素人: { reading: "しろうと", meaning: "amateur,novice" },
  芯: { reading: "しん", meaning: "core,heart,wick,marrow" },
  新幹線: {
    reading: "しんかんせん",
    meaning: "bullet train (very high speed),shinkansen",
  },
  真空: { reading: "しんくう", meaning: "vacuum,hollow,empty" },
  信ずる: {
    reading: "しんずる",
    meaning: "to believe,to believe in,to place trust in",
  },
  心身: { reading: "しんしん", meaning: "mind and body" },
  申請: { reading: "しんせい", meaning: "application,request,petition" },
  人造: { reading: "じんぞう", meaning: "man-made,synthetic,artificial" },
  寝台: { reading: "しんだい", meaning: "bed,couch" },
  診断: { reading: "しんだん", meaning: "diagnosis" },
  侵入: {
    reading: "しんにゅう",
    meaning: "penetration,invasion,raid,aggression,trespass",
  },
  人文科学: {
    reading: "じんぶんかがく",
    meaning: "social sciences,humanities",
  },
  人命: { reading: "じんめい", meaning: "(human) life" },
  深夜: { reading: "しんや", meaning: "late at night" },
  森林: { reading: "しんりん", meaning: "forest,woods" },
  親類: { reading: "しんるい", meaning: "relation,kin" },
  針路: { reading: "しんろ", meaning: "course,direction,compass bearing" },
  神話: { reading: "しんわ", meaning: "myth,legend" },
  酢: { reading: "す", meaning: "vinegar" },
  水産: { reading: "すいさん", meaning: "marine products,fisheries" },
  炊事: { reading: "すいじ", meaning: "cooking,culinary arts" },
  水蒸気: { reading: "すいじょうき", meaning: "water vapour,steam" },
  水素: { reading: "すいそ", meaning: "hydrogen" },
  垂直: { reading: "すいちょく", meaning: "vertical,perpendicular" },
  推定: { reading: "すいてい", meaning: "presumption,assumption,estimation" },
  水滴: { reading: "すいてき", meaning: "drop of water" },
  水筒: { reading: "すいとう", meaning: "canteen,flask,water bottle" },
  随筆: { reading: "ずいひつ", meaning: "essays,miscellaneous writings" },
  水分: { reading: "すいぶん", meaning: "moisture" },
  水平: { reading: "すいへい", meaning: "water level,horizon" },
  水平線: { reading: "すいへいせん", meaning: "horizon" },
  水曜: { reading: "すいよう", meaning: "Wednesday" },
  末っ子: { reading: "すえっこ", meaning: "youngest child" },
  図鑑: { reading: "ずかん", meaning: "picture book" },
  杉: { reading: "すぎ", meaning: "Japanese cedar" },
  好き嫌い: { reading: "すききらい", meaning: "likes and dislikes,taste" },
  好き好き: { reading: "すきずき", meaning: "matter of taste" },
  透き通る: { reading: "すきとおる", meaning: "to be(come) transparent" },
  隙間: { reading: "すきま", meaning: "crevice,crack,gap,opening" },
  図形: { reading: "ずけい", meaning: "figure" },
  鈴: { reading: "すず", meaning: "bell" },
  涼む: {
    reading: "すずむ",
    meaning: "to cool oneself,to cool off,to enjoy evening cool",
  },
  素直: { reading: "すなお", meaning: "obedient,meek,docile,unaffected" },
  頭脳: { reading: "ずのう", meaning: "head,brains,intellect" },
  図表: { reading: "ずひょう", meaning: "chart,diagram,graph" },
  住まい: { reading: "すまい", meaning: "dwelling,house,residence,address" },
  墨: { reading: "すみ", meaning: "ink" },
  澄む: {
    reading: "すむ",
    meaning: "to clear (e.g. weather),to become transparent",
  },
  相撲: { reading: "すもう", meaning: "sumo wrestling" },
  掏摸: { reading: "すり", meaning: "pickpocket" },
  刷る: { reading: "する", meaning: "to print" },
  狡い: { reading: "ずるい", meaning: "sly,cunning" },
  寸法: { reading: "すんぽう", meaning: "measurement,size,dimension" },
  姓: { reading: "せい", meaning: "surname,family name" },
  税関: { reading: "ぜいかん", meaning: "customs house" },
  製作: { reading: "せいさく", meaning: "manufacture,production" },
  制作: { reading: "せいさく", meaning: "work (film, book)" },
  性質: { reading: "せいしつ", meaning: "nature,property,disposition" },
  清書: { reading: "せいしょ", meaning: "clean copy" },
  青少年: { reading: "せいしょうねん", meaning: "youth,young person" },
  整数: { reading: "せいすう", meaning: "integer" },
  清掃: { reading: "せいそう", meaning: "cleaning" },
  生存: { reading: "せいぞん", meaning: "existence,being,survival" },
  生長: { reading: "せいちょう", meaning: "growth,increment" },
  政党: { reading: "せいとう", meaning: "(member of) political party" },
  生年月日: { reading: "せいねんがっぴ", meaning: "birth date" },
  性能: { reading: "せいのう", meaning: "ability,efficiency" },
  整備: { reading: "せいび", meaning: "adjustment,completion,consolidation" },
  成分: { reading: "せいぶん", meaning: "ingredient,component,composition" },
  性別: { reading: "せいべつ", meaning: "distinction by sex,sex,gender" },
  正方形: { reading: "せいほうけい", meaning: "square" },
  正門: { reading: "せいもん", meaning: "main gate,main entrance" },
  成立: {
    reading: "せいりつ",
    meaning: "coming into existence,arrangements,establishment,completion",
  },
  西暦: { reading: "せいれき", meaning: "Christian Era,anno domini (A.D.)" },
  背負う: {
    reading: "せおう",
    meaning: "to be burdened with,to carry on back or shoulder",
  },
  赤道: { reading: "せきどう", meaning: "equator" },
  折角: {
    reading: "せっかく",
    meaning: "with trouble,at great pains,long-awaited",
  },
  接近: {
    reading: "せっきん",
    meaning: "getting closer,drawing nearer,approaching",
  },
  石鹸: { reading: "せっけん", meaning: "soap" },
  接する: {
    reading: "せっする",
    meaning: "to come in contact with,to connect,to attend,to receive",
  },
  接続: {
    reading: "せつぞく",
    meaning: "(1) connection,union,join,link,(2) changing trains",
  },
  瀬戸物: { reading: "せともの", meaning: "earthenware,crockery,china" },
  迫る: { reading: "せまる", meaning: "to draw near,to press" },
  攻める: { reading: "せめる", meaning: "to attack,to assault" },
  栓: { reading: "せん", meaning: "stopper,cork,stopcock" },
  前後: {
    reading: "ぜんご",
    meaning:
      "around,throughout,front and back,before and behind,before and after",
  },
  洗剤: { reading: "せんざい", meaning: "detergent,washing material" },
  全集: { reading: "ぜんしゅう", meaning: "complete works" },
  全身: {
    reading: "ぜんしん",
    meaning: "the whole body,full-length (portrait)",
  },
  扇子: { reading: "せんす", meaning: "folding fan" },
  専制: { reading: "せんせい", meaning: "despotism,autocracy" },
  先々月: { reading: "せんせんげつ", meaning: "month before last" },
  先祖: { reading: "せんぞ", meaning: "ancestor" },
  先端: { reading: "せんたん", meaning: "pointed end,tip,fine point" },
  宣伝: { reading: "せんでん", meaning: "propaganda,publicity" },
  先頭: { reading: "せんとう", meaning: "head,lead,vanguard,first" },
  全般: {
    reading: "ぜんぱん",
    meaning: "(the) whole,universal,wholly,general",
  },
  扇風機: { reading: "せんぷうき", meaning: "electric fan" },
  線路: { reading: "せんろ", meaning: "line,track,roadbed" },
  相違: { reading: "そうい", meaning: "difference,discrepancy,variation" },
  雑巾: { reading: "ぞうきん", meaning: "house-cloth,dust cloth" },
  増減: { reading: "ぞうげん", meaning: "increase and decrease,fluctuation" },
  倉庫: { reading: "そうこ", meaning: "storehouse,warehouse,godown" },
  相互: { reading: "そうご", meaning: "mutual,reciprocal" },
  創作: { reading: "そうさく", meaning: "production,literary creation,work" },
  葬式: { reading: "そうしき", meaning: "funeral" },
  造船: { reading: "ぞうせん", meaning: "shipbuilding" },
  騒々しい: { reading: "そうぞうしい", meaning: "noisy,boisterous" },
  増大: { reading: "ぞうだい", meaning: "enlargement" },
  送別: { reading: "そうべつ", meaning: "farewell,send-off" },
  草履: { reading: "ぞうり", meaning: "zoori (Japanese footwear),sandals" },
  総理大臣: { reading: "そうりだいじん", meaning: "Prime Minister" },
  送料: { reading: "そうりょう", meaning: "postage,carriage" },
  属する: {
    reading: "ぞくする",
    meaning:
      "to belong to,to come under,to be affiliated with,to be subject to",
  },
  続々: { reading: "ぞくぞく", meaning: "successively,one after another" },
  速達: { reading: "そくたつ", meaning: "express,special delivery" },
  測定: { reading: "そくてい", meaning: "measurement" },
  測量: { reading: "そくりょう", meaning: "measurement,surveying" },
  速力: { reading: "そくりょく", meaning: "speed" },
  素質: { reading: "そしつ", meaning: "character,qualities,genius" },
  祖先: { reading: "そせん", meaning: "ancestor" },
  卒直: { reading: "そっちょく", meaning: "frankness,candour,openheartedness" },
  具える: { reading: "そなえる", meaning: "to be furnished with" },
  蕎麦: { reading: "そば", meaning: "soba (buckwheat noodles)" },
  剃る: { reading: "そる", meaning: "to shave" },
  逸れる: {
    reading: "それる",
    meaning: "to stray (turn) from subject,to get lost,to go astray",
  },
  揃う: {
    reading: "そろう",
    meaning: "to become complete,to be equal,to be all present,to gather",
  },
  揃える: {
    reading: "そろえる",
    meaning:
      "to put things in order,to arrange,to make uniform,to get something ready",
  },
  算盤: { reading: "そろばん", meaning: "abacus" },
  存じる: { reading: "ぞんじる", meaning: "(hum) to know" },
  損得: {
    reading: "そんとく",
    meaning: "loss and gain,advantage and disadvantage",
  },
  田ぼ: { reading: "たんぼ", meaning: "paddy field,farm" },
  だいいち: { reading: "（副）", meaning: "first,foremost,# 1" },
  退院: { reading: "たいいん", meaning: "leaving hospital" },
  大学院: { reading: "だいがくいん", meaning: "graduate school" },
  大工: { reading: "だいく", meaning: "carpenter" },
  体系: { reading: "たいけい", meaning: "system,organization" },
  太鼓: { reading: "たいこ", meaning: "drum,tambourine" },
  対策: { reading: "たいさく", meaning: "counter-plan,counter-measure" },
  大して: { reading: "たいして", meaning: "(not so) much,(not) very" },
  対照: { reading: "たいしょう", meaning: "contrast,antithesis,comparison" },
  大小: { reading: "だいしょう", meaning: "size" },
  体制: {
    reading: "たいせい",
    meaning: "order,system,structure,set-up,organization",
  },
  体積: { reading: "たいせき", meaning: "capacity,volume" },
  大層: { reading: "たいそう", meaning: "very much,exaggerated,very fine" },
  体操: {
    reading: "たいそう",
    meaning: "gymnastics,physical exercises,calisthenics",
  },
  大分: { reading: "だいぶん", meaning: "considerably,greatly,a lot" },
  大木: { reading: "たいぼく", meaning: "large tree" },
  題名: { reading: "だいめい", meaning: "title" },
  代名詞: { reading: "だいめいし", meaning: "pronoun" },
  田植え: { reading: "たうえ", meaning: "rice planting" },
  絶えず: { reading: "たえず", meaning: "constantly" },
  楕円: { reading: "だえん", meaning: "ellipse" },
  高める: { reading: "たかめる", meaning: "to raise,to lift,to boost" },
  耕す: { reading: "たがやす", meaning: "to till,to plow,to cultivate" },
  滝: { reading: "たき", meaning: "waterfall" },
  炊く: { reading: "たく", meaning: "to boil,to cook　（米）" },
  焚く: { reading: "たく", meaning: "to burn,to kindle,to build a fire" },
  蓄える: { reading: "たくわえる", meaning: "to store,to lay in stock" },
  竹: {
    reading: "たけ",
    meaning: "bamboo,middle (of a three-tier ranking system)",
  },
  助かる: {
    reading: "たすかる",
    meaning: "to be saved,to be rescued,to survive,to be helpful",
  },
  只: {
    reading: "ただ",
    meaning: "free of charge,mere,sole,only,usual,common",
  },
  但し: { reading: "ただし", meaning: "but,however,provided that" },
  畳む: { reading: "たたむ", meaning: "to fold (clothes)" },
  立ち止まる: {
    reading: "たちどまる",
    meaning: "to stop,to halt,to stand still",
  },
  建つ: { reading: "たつ", meaning: "to erect,to be erected,to be built" },
  発つ: { reading: "たつ", meaning: "to depart (on a plane, train, etc.)" },
  脱線: { reading: "だっせん", meaning: "derailment,digression" },
  妥当: { reading: "だとう", meaning: "valid,proper,right,appropriate" },
  例える: {
    reading: "たとえる",
    meaning:
      "to compare,to liken,to speak figuratively,to illustrate,to use a simile",
  },
  頼もしい: {
    reading: "たのもしい",
    meaning: "reliable,trustworthy,hopeful,promising",
  },
  足袋: { reading: "たび", meaning: "tabi,Japanese socks (with split toe)" },
  溜まる: { reading: "たまる", meaning: "to collect,to gather,to save" },
  溜息: { reading: "ためいき", meaning: "a sigh" },
  溜める: { reading: "ためる", meaning: "to amass,to accumulate" },
  足る: { reading: "たる", meaning: "to be sufficient,to be enough" },
  段階: { reading: "だんかい", meaning: "gradation,grade,stage" },
  短期: { reading: "たんき", meaning: "short term" },
  炭鉱: { reading: "たんこう", meaning: "coal mine,coal pit" },
  短所: {
    reading: "たんしょ",
    meaning: "(1) defect,demerit,weak point,(2) disadvantage",
  },
  淡水: { reading: "たんすい", meaning: "fresh water" },
  断水: { reading: "だんすい", meaning: "water outage" },
  単数: { reading: "たんすう", meaning: "singular (number)" },
  団地: { reading: "だんち", meaning: "multi-unit apartments" },
  断定: { reading: "だんてい", meaning: "conclusion,decision" },
  短編: { reading: "たんぺん", meaning: "short (e.g. story, film)" },
  誓う: {
    reading: "ちかう",
    meaning: "to swear,to vow,to take an oath,to pledge",
  },
  地下水: { reading: "ちかすい", meaning: "underground water" },
  近々: { reading: "ちかぢか", meaning: "nearness,before long" },
  近付ける: {
    reading: "ちかづける",
    meaning: "to bring near,to put close,to let come near,to associate with",
  },
  近寄る: { reading: "ちかよる", meaning: "to approach,to draw near" },
  力強い: { reading: "ちからづよい", meaning: "reassuring,emboldened" },
  地質: { reading: "ちしつ", meaning: "geological features" },
  知人: { reading: "ちじん", meaning: "friend,acquaintance" },
  地帯: { reading: "ちたい", meaning: "area,zone" },
  縮む: { reading: "ちぢむ", meaning: "to shrink,to be contracted" },
  縮める: {
    reading: "ちぢめる",
    meaning: "to shorten,to reduce,to boil down,to shrink",
  },
  縮れる: { reading: "ちぢれる", meaning: "to be wavy,to be curled" },
  地点: { reading: "ちてん", meaning: "site,point on a map" },
  地名: { reading: "ちめい", meaning: "place name" },
  着々: { reading: "ちゃくちゃく", meaning: "steadily" },
  茶碗: { reading: "ちゃわん", meaning: "rice bowl,tea cup,teacup" },
  中間: { reading: "ちゅうかん", meaning: "middle,midway,interim" },
  中旬: { reading: "ちゅうじゅん", meaning: "second third of a month" },
  抽象: { reading: "ちゅうしょう", meaning: "abstract" },
  中世: { reading: "ちゅうせい", meaning: "Middle Ages,mediaeval times" },
  中性: {
    reading: "ちゅうせい",
    meaning: "neuter gender,neutral (chem.),indifference,sterility",
  },
  中途: { reading: "ちゅうと", meaning: "in the middle,half-way" },
  中年: { reading: "ちゅうねん", meaning: "middle-aged" },
  超過: { reading: "ちょうか", meaning: "excess,being more than" },
  彫刻: { reading: "ちょうこく", meaning: "carving,engraving,sculpture" },
  長所: {
    reading: "ちょうしょ",
    meaning: "(1) strong point,merit,(2) advantage",
  },
  長女: { reading: "ちょうじょ", meaning: "eldest daughter" },
  調整: { reading: "ちょうせい", meaning: "regulation,adjustment,tuning" },
  調節: { reading: "ちょうせつ", meaning: "regulation,adjustment,control" },
  長短: { reading: "ちょうたん", meaning: "length,long and short,+-" },
  頂点: { reading: "ちょうてん", meaning: "top,summit" },
  長男: { reading: "ちょうなん", meaning: "eldest son" },
  長方形: { reading: "ちょうほうけい", meaning: "rectangle,oblong" },
  調味料: { reading: "ちょうみりょう", meaning: "condiment,seasoning" },
  直後: { reading: "ちょくご", meaning: "immediately following" },
  直線: { reading: "ちょくせん", meaning: "straight line" },
  直前: { reading: "ちょくぜん", meaning: "just before" },
  直通: { reading: "ちょくつう", meaning: "direct communication" },
  直流: { reading: "ちょくりゅう", meaning: "direct current" },
  貯蔵: { reading: "ちょぞう", meaning: "storage,preservation" },
  直角: { reading: "ちょっかく", meaning: "right angle" },
  直径: { reading: "ちょっけい", meaning: "diameter" },
  散らかす: {
    reading: "ちらかす",
    meaning: "to scatter around,to leave untidy",
  },
  散らかる: {
    reading: "ちらかる",
    meaning: "to be in disorder,to lie scattered around",
  },
  散らす: {
    reading: "ちらす",
    meaning: "to scatter,to disperse,to distribute",
  },
  塵紙: { reading: "ちりがみ", meaning: "tissue paper,toilet paper" },
  散る: { reading: "ちる", meaning: "to fall,to scatter (e.g. blossoms)" },
  追加: { reading: "ついか", meaning: "addition,supplement,appendix" },
  通貨: { reading: "つうか", meaning: "currency" },
  通勤: { reading: "つうきん", meaning: "commuting to work" },
  通知: { reading: "つうち", meaning: "notice,notification" },
  通帳: { reading: "つうちょう", meaning: "passbook" },
  通訳: { reading: "つうやく", meaning: "interpretation" },
  通用: { reading: "つうよう", meaning: "popular use,circulation" },
  通路: { reading: "つうろ", meaning: "passage,pathway" },
  付合う: {
    reading: "つきあう",
    meaning: "to associate with,to keep company with,to get on with",
  },
  突き当たり: { reading: "つきあたり", meaning: "end (e.g. of street)" },
  突き当たる: { reading: "つきあたる", meaning: "to run into,to collide with" },
  月日: { reading: "つきひ", meaning: "time,years,days" },
  点く: { reading: "つく", meaning: "to catch fire,(electricity) comes on" },
  突く: { reading: "つく", meaning: "(1) to thrust,to strike,(2) to poke" },
  次ぐ: { reading: "つぐ", meaning: "to rank next to,to come after" },
  "作る/造る": { reading: "つくる", meaning: "to make,to create" },
  着ける: {
    reading: "つける",
    meaning: "(1) to attach,to join,to add,to append",
  },
  点ける: { reading: "つける", meaning: "to turn on,to switch on,to light up" },
  浸ける: { reading: "つける", meaning: "to dip in,to soak" },
  伝わる: {
    reading: "つたわる",
    meaning: "to be handed down,to be introduced,to be transmitted",
  },
  突っ込む: {
    reading: "つっこむ",
    meaning: "to plunge into,to go into deeply",
  },
  務める: {
    reading: "つとめる",
    meaning: "(1) to serve,to fill a post,to serve under,to work (for)",
  },
  努める: {
    reading: "つとめる",
    meaning: "(1) to serve,to fill a post,to serve under,to work (for)",
  },
  綱: { reading: "つな", meaning: "rope" },
  繋がり: { reading: "つながり", meaning: "connection,link,relationship" },
  繋がる: {
    reading: "つながる",
    meaning: "to be tied together,to be connected to,to be related to",
  },
  繋げる: { reading: "つなげる", meaning: "to connect" },
  粒: { reading: "つぶ", meaning: "grain" },
  潰す: { reading: "つぶす", meaning: "to smash,to waste" },
  潰れる: { reading: "つぶれる", meaning: "to be smashed,to go bankrupt" },
  詰まる: { reading: "つまる", meaning: "to be blocked,to be packed" },
  積む: { reading: "つむ", meaning: "to pile up,to stack" },
  爪: { reading: "つめ", meaning: "fingernail or toenail,claw,talon,hoof" },
  艶: { reading: "つや", meaning: "gloss,glaze" },
  強気: { reading: "つよき", meaning: "firm,strong" },
  釣り合う: {
    reading: "つりあう",
    meaning: "to balance,to be in harmony,to suit",
  },
  吊る: { reading: "つる", meaning: "to hang" },
  吊す: { reading: "つるす", meaning: "to hang" },
  出合い: { reading: "であい", meaning: "an encounter" },
  手洗い: { reading: "てあらい", meaning: "restroom,lavatory,hand-washing" },
  定員: {
    reading: "ていいん",
    meaning: "fixed number of regular personnel,capacity (of boat, etc.)",
  },
  定価: { reading: "ていか", meaning: "established price" },
  低下: { reading: "ていか", meaning: "fall,decline,lowering,deterioration" },
  定期券: { reading: "ていきけん", meaning: "commuter pass,season ticket" },
  定休日: { reading: "ていきゅうび", meaning: "regular holiday" },
  停止: { reading: "ていし", meaning: "suspension,interruption,stoppage,ban" },
  停車: { reading: "ていしゃ", meaning: "stopping (e.g. train)" },
  停電: { reading: "ていでん", meaning: "failure of electricity" },
  出入り: {
    reading: "でいり",
    meaning:
      "in and out,coming and going,free association,income and expenditure,debits and credit",
  },
  出入口: { reading: "でいりぐち", meaning: "exit and entrance" },
  手入れ: { reading: "ていれ", meaning: "repairs,maintenance" },
  出掛ける: {
    reading: "でかける",
    meaning: "to depart,to set out,to start,to be going out",
  },
  出来上がり: {
    reading: "できあがり",
    meaning: "be finished,ready,made for,cut out",
  },
  出来上がる: {
    reading: "できあがる",
    meaning:
      "(1) to be finished,to be ready,by definition,(2) to be very drunk",
  },
  的確: { reading: "てきかく", meaning: "precise,accurate" },
  適確: { reading: "てきかく", meaning: "precise,accurate" },
  手首: { reading: "てくび", meaning: "wrist" },
  凸凹: { reading: "でこぼこ", meaning: "unevenness,roughness,ruggedness" },
  手頃: { reading: "てごろ", meaning: "moderate,handy" },
  手帳: { reading: "てちょう", meaning: "notebook" },
  鉄橋: { reading: "てっきょう", meaning: "railway bridge,iron bridge" },
  手続き: {
    reading: "てつづき",
    meaning: "procedure,(legal) process,formalities",
  },
  鉄砲: { reading: "てっぽう", meaning: "gun" },
  手拭い: { reading: "てぬぐい", meaning: "(hand) towel" },
  手前: { reading: "てまえ", meaning: "before,this side,we,you" },
  出迎え: { reading: "でむかえ", meaning: "meeting,reception" },
  出迎える: { reading: "でむかえる", meaning: "to meet,to greet" },
  照らす: { reading: "てらす", meaning: "to shine on,to illuminate" },
  照る: { reading: "てる", meaning: "to shine" },
  展開: {
    reading: "てんかい",
    meaning: "develop,expansion (opposite of compression)",
  },
  伝記: { reading: "でんき", meaning: "biography,life story" },
  電球: { reading: "でんきゅう", meaning: "light bulb" },
  点数: { reading: "てんすう", meaning: "marks,points,score,runs" },
  伝染: { reading: "でんせん", meaning: "contagion" },
  電池: { reading: "でんち", meaning: "battery" },
  点々: { reading: "てんてん", meaning: "here and there,little by little" },
  電柱: {
    reading: "でんちゅう",
    meaning: "telephone pole,telegraph pole,lightpole",
  },
  天皇: { reading: "てんのう", meaning: "Emperor of Japan" },
  電波: { reading: "でんぱ", meaning: "electro-magnetic wave" },
  電流: { reading: "でんりゅう", meaning: "electric current" },
  電力: { reading: "でんりょく", meaning: "electric power" },
  問い合わせ: { reading: "といあわせ", meaning: "enquiry,ENQ" },
  銅: { reading: "どう", meaning: "copper" },
  統一: { reading: "とういつ", meaning: "unity,consolidation,uniformity" },
  同格: { reading: "どうかく", meaning: "the same rank,equality,apposition" },
  峠: { reading: "とうげ", meaning: "ridge,(mountain) pass,difficult part" },
  統計: { reading: "とうけい", meaning: "scattering,a scatter,dispersion" },
  動作: {
    reading: "どうさ",
    meaning: "action,movements,motions,bearing,behaviour,manners",
  },
  東西: { reading: "とうざい", meaning: "East and West,whole country" },
  当日: { reading: "とうじつ", meaning: "appointed day,very day" },
  投書: {
    reading: "とうしょ",
    meaning: "letter to the editor,letter from a reader,contribution",
  },
  登場: { reading: "とうじょう", meaning: "entry (on stage)" },
  灯台: { reading: "とうだい", meaning: "lighthouse" },
  盗難: { reading: "とうなん", meaning: "theft,robbery" },
  当番: { reading: "とうばん", meaning: "being on duty" },
  等分: { reading: "とうぶん", meaning: "division into equal parts" },
  透明: { reading: "とうめい", meaning: "transparency,cleanness" },
  灯油: { reading: "とうゆ", meaning: "lamp oil,kerosene" },
  東洋: { reading: "とうよう", meaning: "Orient" },
  童話: { reading: "どうわ", meaning: "fairy tale" },
  通り掛かる: { reading: "とおりかかる", meaning: "to happen to pass by" },
  溶かす: { reading: "とかす", meaning: "to melt,to dissolve" },
  尖る: {
    reading: "とがる",
    meaning:
      "to taper to a point,to become sharp,to be sour,to look displeased",
  },
  溶く: { reading: "とく", meaning: "to dissolve (paint)" },
  退く: { reading: "どく", meaning: "(1) to retreat,to recede,to withdraw" },
  特殊: { reading: "とくしゅ", meaning: "special,unique" },
  特色: { reading: "とくしょく", meaning: "characteristic,feature" },
  特長: { reading: "とくちょう", meaning: "forte,merit" },
  特定: { reading: "とくてい", meaning: "specific,special,particular" },
  特売: { reading: "とくばい", meaning: "special sale" },
  溶け込む: { reading: "とけこむ", meaning: "to melt into" },
  溶ける: { reading: "とける", meaning: "to melt,to thaw,to fuse,to dissolve" },
  退ける: {
    reading: "どける",
    meaning:
      "to remove,to take away,to dislodge,to put something out of the way",
  },
  床の間: { reading: "とこのま", meaning: "alcove" },
  床屋: { reading: "とこや", meaning: "barber" },
  所々: {
    reading: "ところどころ",
    meaning: "here and there,some parts (of something)",
  },
  都心: { reading: "としん", meaning: "heart (of city)" },
  戸棚: { reading: "とだな", meaning: "cupboard,locker,closet,wardrobe" },
  整う: {
    reading: "ととのう",
    meaning: "to be prepared,to be in order,to be put in order,to be arranged",
  },
  留まる: {
    reading: "とどまる",
    meaning: "(1) to be fixed,(2) to abide,to stay (in the one place)",
  },
  飛び込む: {
    reading: "とびこむ",
    meaning: "to jump in,to leap in,to plunge into,to dive",
  },
  跳ぶ: { reading: "とぶ", meaning: "to jump,to fly,to leap" },
  留まる: {
    reading: "とまる",
    meaning: "(1) to be fixed,(2) to abide,to stay (in the one place)",
  },
  泊める: { reading: "とめる", meaning: "to give shelter to,to lodge" },
  捕える: {
    reading: "とらえる",
    meaning: "to seize,to grasp,to capture,to arrest",
  },
  取り入れる: {
    reading: "とりいれる",
    meaning: "to harvest,to take in,to adopt",
  },
  取り消す: { reading: "とりけす", meaning: "to cancel" },
  取り出す: {
    reading: "とりだす",
    meaning: "to take out,to produce,to pick out",
  },
  採る: {
    reading: "とる",
    meaning: "(1) to adopt (measure, proposal),(2) to pick (fruit)",
  },
  捕る: { reading: "とる", meaning: "to take,to catch (fish),to capture" },
  丼: {
    reading: "どんぶり",
    meaning: "porcelain bowl,bowl of rice with food on top",
  },
  内科: { reading: "ないか", meaning: "internist clinic,internal medicine" },
  内線: {
    reading: "ないせん",
    meaning: "phone extension,indoor wiring,inner line",
  },
  治す: {
    reading: "なおす",
    meaning: "to cure,to heal,to fix,to correct,to repair",
  },
  永い: { reading: "ながい", meaning: "long,lengthy" },
  仲直り: { reading: "なかなおり", meaning: "reconciliation,make peace with" },
  長引く: { reading: "ながびく", meaning: "to be prolonged,to drag on" },
  中身: {
    reading: "なかみ",
    meaning: "contents,interior,substance,filling,(sword) blade",
  },
  中味: {
    reading: "なかみ",
    meaning: "contents,interior,substance,filling,(sword) blade",
  },
  中指: { reading: "なかゆび", meaning: "middle finger" },
  仲良し: { reading: "なかよし", meaning: "intimate friend,bosom buddy,chum" },
  慰める: { reading: "なぐさめる", meaning: "to comfort,to console" },
  亡くす: { reading: "なくす", meaning: "to lose someone, wife, child, etc" },
  為す: { reading: "なす", meaning: "to accomplish,to do" },
  謎謎: { reading: "なぞなぞ", meaning: "riddle,puzzle,enigma" },
  懐かしい: { reading: "なつかしい", meaning: "dear,desired,missed" },
  撫でる: { reading: "なでる", meaning: "to brush gently,to stroke" },
  斜め: { reading: "ななめ", meaning: "obliqueness" },
  何々: { reading: "なになに", meaning: "such and such,What?" },
  何分: { reading: "なにぶん", meaning: "what minute?,how many minutes?" },
  生意気: {
    reading: "なまいき",
    meaning: "impertinent,saucy,cheeky,conceit,audacious,brazen",
  },
  並木: { reading: "なみき", meaning: "roadside tree,row of trees" },
  倣う: { reading: "ならう", meaning: "to imitate,to follow,to emulate" },
  鳴らす: {
    reading: "ならす",
    meaning: "to ring,to sound,to chime,to beat,to snort (nose)",
  },
  生る: { reading: "なる", meaning: "to bear fruit" },
  馴れる: {
    reading: "なれる",
    meaning: "to become domesticated,to become tame",
  },
  南極: { reading: "なんきょく", meaning: "south pole,Antarctic" },
  南米: { reading: "なんべい", meaning: "South America" },
  南北: { reading: "なんぼく", meaning: "south and north" },
  煮える: { reading: "にえる", meaning: "to boil,to cook,to be cooked" },
  匂う: { reading: "におう", meaning: "to be fragrant,to smell,to stink" },
  逃がす: {
    reading: "にがす",
    meaning: "to let loose,to set free,to let escape",
  },
  憎い: {
    reading: "にくい",
    meaning: "hateful,abominable,poor-looking,detestable",
  },
  憎む: { reading: "にくむ", meaning: "to hate,to detest" },
  憎らしい: { reading: "にくらしい", meaning: "odious,hateful" },
  濁る: { reading: "にごる", meaning: "to become muddy,to get impure" },
  虹: { reading: "にじ", meaning: "rainbow" },
  日時: { reading: "にちじ", meaning: "date and time" },
  日用品: { reading: "にちようひん", meaning: "daily necessities" },
  日課: { reading: "にっか", meaning: "daily lesson,daily work,daily routine" },
  日程: { reading: "にってい", meaning: "agenda" },
  鈍い: {
    reading: "にぶい",
    meaning: "dull (e.g. a knife),thickheaded,slow (opposite of fast),stupid",
  },
  入社: { reading: "にゅうしゃ", meaning: "entry to a company" },
  女房: { reading: "にょうぼう", meaning: "wife" },
  睨む: {
    reading: "にらむ",
    meaning: "to glare at,to scowl at,to keep an eye on",
  },
  煮る: { reading: "にる", meaning: "to boil,to cook" },
  俄: {
    reading: "にわか",
    meaning: "sudden,abrupt,unexpected,improvised,offhand",
  },
  縫う: { reading: "ぬう", meaning: "to sew" },
  濡らす: { reading: "ぬらす", meaning: "to wet,to soak,to dip" },
  捩る: { reading: "ねじる", meaning: "to twist" },
  熱する: { reading: "ねっする", meaning: "to heat" },
  寝間着: {
    reading: "ねまき",
    meaning: "sleep-wear,nightclothes,pyjamas,nightgown,nightdress",
  },
  寝巻: {
    reading: "ねまき",
    meaning: "sleep-wear,nightclothes,pyjamas,nightgown,nightdress",
  },
  狙い: { reading: "ねらい", meaning: "aim" },
  狙う: { reading: "ねらう", meaning: "to aim at" },
  年度: { reading: "ねんど", meaning: "year,fiscal year,school year,term" },
  農産物: { reading: "のうさんぶつ", meaning: "agricultural produce" },
  農村: {
    reading: "のうそん",
    meaning: "agricultural community,farm village,rural",
  },
  濃度: { reading: "のうど", meaning: "concentration,brightness" },
  農薬: { reading: "のうやく", meaning: "agricultural chemicals" },
  能率: { reading: "のうりつ", meaning: "efficiency" },
  残らず: {
    reading: "のこらず",
    meaning: "all,entirely,completely,without exception",
  },
  載せる: {
    reading: "のせる",
    meaning: "to place on (something),to take on board,to give a ride",
  },
  覗く: {
    reading: "のぞく",
    meaning: "to peep in,to look in,to peek in,to stick out",
  },
  延ばす: {
    reading: "のばす",
    meaning: "to lengthen,to stretch,to reach out,to grow (beard)",
  },
  延びる: { reading: "のびる", meaning: "to be prolonged" },
  上り: { reading: "のぼり", meaning: "up-train (going to Tokyo),ascent" },
  上る: { reading: "のぼる", meaning: "to ascend,to go up,to climb" },
  糊: { reading: "のり", meaning: "paste,starch" },
  乗換: { reading: "のりかえ", meaning: "(n) transfer (trains, buses, etc.)" },
  載る: { reading: "のる", meaning: "to appear (in print),to be recorded" },
  鈍い: {
    reading: "のろい",
    meaning: "dull (e.g. a knife),thickheaded,slow (opposite of fast),stupid",
  },
  呑気: {
    reading: "のんき",
    meaning: "carefree,optimistic,careless,reckless,heedless",
  },
  灰色: { reading: "はいいろ", meaning: "grey,gray,ashen" },
  俳句: { reading: "はいく", meaning: "haiku poetry" },
  拝見: { reading: "はいけん", meaning: "(hum) (pol) seeing,look at" },
  売店: { reading: "ばいてん", meaning: "shop,stand" },
  売買: { reading: "ばいばい", meaning: "trade,buying and selling" },
  這う: { reading: "はう", meaning: "to creep,to crawl" },
  生える: {
    reading: "はえる",
    meaning: "(1) to grow,to spring up,(2) to cut (teeth)",
  },
  剥す: {
    reading: "はがす",
    meaning: "(v5s) to tear off,to peel off,to rip off",
  },
  秤: { reading: "はかり", meaning: "scales,weighing machine" },
  量る: { reading: "はかる", meaning: "to measure,to weigh,to survey" },
  測る: { reading: "はかる", meaning: "to measure,to weigh,to survey" },
  吐き気: { reading: "はきけ", meaning: "nausea,sickness in the stomach" },
  掃く: { reading: "はく", meaning: "to sweep,to brush,to gather up" },
  歯車: { reading: "はぐるま", meaning: "gear,cog-wheel" },
  挟まる: { reading: "はさまる", meaning: "to get between,to be caught in" },
  挟む: {
    reading: "はさむ",
    meaning: "to interpose,to hold between,to insert",
  },
  箸: { reading: "はし", meaning: "chopsticks" },
  梯子: { reading: "はしご", meaning: "ladder,stairs" },
  始めに: { reading: "はじめに", meaning: "to begin with,first of all" },
  外れる: {
    reading: "はずれる",
    meaning:
      "to be disconnected,to get out of place,to be off,to be out (e.g. of gear)",
  },
  肌着: { reading: "はだぎ", meaning: "underwear" },
  果して: { reading: "はたして", meaning: "as was expected,really" },
  鉢: { reading: "はち", meaning: "a bowl,a pot" },
  発揮: {
    reading: "はっき",
    meaning: "exhibition,demonstration,utilization,display",
  },
  発射: { reading: "はっしゃ", meaning: "firing,shooting,discharge,catapult" },
  発想: {
    reading: "はっそう",
    meaning: "expression (music),conceptualization",
  },
  発電: { reading: "はつでん", meaning: "generation (e.g. power)" },
  発売: { reading: "はつばい", meaning: "sale" },
  派手: { reading: "はで", meaning: "showy,loud,gay,flashy,gaudy" },
  話合い: { reading: "はなしあい", meaning: "discussion,conference" },
  話し掛ける: {
    reading: "はなしかける",
    meaning: "to accost a person,to talk (to someone)",
  },
  話中: { reading: "はなしちゅう", meaning: "while talking,the line is busy" },
  甚だしい: { reading: "はなはだしい", meaning: "extreme,excessive,terrible" },
  花火: { reading: "はなび", meaning: "fireworks" },
  花嫁: { reading: "はなよめ", meaning: "bride" },
  放れる: {
    reading: "はなれる",
    meaning: "to leave,to get free,to cut oneself off",
  },
  羽根: { reading: "はね", meaning: "shuttlecock" },
  跳ねる: { reading: "はねる", meaning: "to jump,to leap" },
  破片: { reading: "はへん", meaning: "fragment,splinter,broken piece" },
  歯磨き: { reading: "はみがき", meaning: "dentifrice,toothpaste" },
  早口: { reading: "はやくち", meaning: "fast-talking" },
  流行る: {
    reading: "はやる",
    meaning: "to flourish,to thrive,to be popular,to come into fashion",
  },
  払い込む: { reading: "はらいこむ", meaning: "to deposit,to pay in" },
  払い戻す: { reading: "はらいもどす", meaning: "to repay,to pay back" },
  針金: { reading: "はりがね", meaning: "wire" },
  張り切る: {
    reading: "はりきる",
    meaning: "to be in high spirits,to be full of vigor",
  },
  反映: { reading: "はんえい", meaning: "reflection,influence" },
  半径: { reading: "はんけい", meaning: "radius" },
  判子: { reading: "はんこ", meaning: "seal (used for signature)" },
  万歳: { reading: "ばんざい", meaning: "hurrah, cheers" },
  判事: { reading: "はんじ", meaning: "judge,judiciary" },
  反省: {
    reading: "はんせい",
    meaning:
      "reflection,reconsideration,introspection,meditation,contemplation",
  },
  番地: { reading: "ばんち", meaning: "house number,address" },
  半島: { reading: "はんとう", meaning: "peninsula" },
  日当たり: { reading: "ひあたり", meaning: "exposure to the sun,sunny place" },
  日帰り: { reading: "ひがえり", meaning: "day trip" },
  比較的: { reading: "ひかくてき", meaning: "comparatively,relatively" },
  日陰: { reading: "ひかげ", meaning: "shadow" },
  引受る: {
    reading: "ひきうける",
    meaning: "to undertake,to take up,to take over",
  },
  引返す: {
    reading: "ひきかえす",
    meaning: "to repeat,to send back,to bring back",
  },
  引算: { reading: "ひきざん", meaning: "subtraction" },
  引出す: {
    reading: "ひきだす",
    meaning: "to pull out,to take out,to draw out,to withdraw",
  },
  引き止める: {
    reading: "ひきとめる",
    meaning: "to detain,to check,to restrain",
  },
  卑怯: { reading: "ひきょう", meaning: "cowardice,meanness,unfairness" },
  引分け: { reading: "ひきわけ", meaning: "a draw (in competition),tie game" },
  髭: { reading: "ひげ", meaning: "moustache,beard,whiskers" },
  陽射: { reading: "ひざし", meaning: "sunlight,rays of the sun" },
  肘: { reading: "ひじ", meaning: "elbow" },
  引っ掛かる: {
    reading: "ひっかかる",
    meaning: "to be caught in,to be stuck in,to be cheated",
  },
  筆記: { reading: "ひっき", meaning: "(taking) notes,copying" },
  引っ繰り返す: {
    reading: "ひっくりかえす",
    meaning:
      "to turn over,to overturn,to knock over,to upset,to turn inside out",
  },
  引っ繰り返る: {
    reading: "ひっくりかえる",
    meaning: "to be overturned,to be upset,to topple over,to be reversed",
  },
  引越し: {
    reading: "ひっこし",
    meaning: "moving (dwelling etc.),changing residence",
  },
  引っ込む: { reading: "ひっこむ", meaning: "to draw back,to sink,to cave in" },
  筆者: { reading: "ひっしゃ", meaning: "writer,author" },
  必需品: {
    reading: "ひつじゅひん",
    meaning: "necessities,necessary article,requisite,essential",
  },
  人差指: { reading: "ひとさしゆび", meaning: "index finger" },
  一通り: {
    reading: "ひととおり",
    meaning: "ordinary,usual,in general,briefly",
  },
  人通り: { reading: "ひとどおり", meaning: "pedestrian traffic" },
  瞳: { reading: "ひとみ", meaning: "pupil (of eye)" },
  一休み: { reading: "ひとやすみ", meaning: "a rest" },
  独り言: {
    reading: "ひとりごと",
    meaning: "a soliloquy,a monologue,speaking to oneself",
  },
  皮肉: { reading: "ひにく", meaning: "cynicism,sarcasm" },
  日日: { reading: "ひにち", meaning: "every day,daily,day after day" },
  捻る: {
    reading: "ひねる",
    meaning: "to turn (a switch) on or off,to twist,to puzzle over",
  },
  日の入り: { reading: "ひのいり", meaning: "sunset" },
  日の出: { reading: "ひので", meaning: "sunrise" },
  響き: { reading: "ひびき", meaning: "echo,sound,reverberation,noise" },
  響く: { reading: "ひびく", meaning: "to resound" },
  皮膚: { reading: "ひふ", meaning: "skin" },
  冷やす: { reading: "ひやす", meaning: "to cool,to refrigerate" },
  美容: { reading: "びよう", meaning: "beauty of figure or form" },
  表紙: { reading: "ひょうし", meaning: "front cover,binding" },
  標識: { reading: "ひょうしき", meaning: "sign,mark" },
  標準: { reading: "ひょうじゅん", meaning: "standard,level" },
  標本: { reading: "ひょうほん", meaning: "example,specimen" },
  評論: { reading: "ひょうろん", meaning: "criticism,critique" },
  平仮名: {
    reading: "ひらがな",
    meaning: "hiragana,47 syllables,the cursive syllabary",
  },
  昼寝: { reading: "ひるね", meaning: "nap (at home),siesta" },
  広げる: {
    reading: "ひろげる",
    meaning: "to spread,to extend,to expand,to enlarge",
  },
  広さ: { reading: "ひろさ", meaning: "extent" },
  広場: { reading: "ひろば", meaning: "plaza" },
  広々: { reading: "ひろびろ", meaning: "extensive,spacious" },
  広める: { reading: "ひろめる", meaning: "to broaden,to propagate" },
  便箋: { reading: "びんせん", meaning: "writing paper,stationery" },
  瓶詰: { reading: "びんづめ", meaning: "bottling,bottled" },
  風船: { reading: "ふうせん", meaning: "balloon" },
  不運: { reading: "ふうん", meaning: "unlucky,misfortune,bad luck,fate" },
  殖える: { reading: "ふえる", meaning: "to increase,to multiply" },
  深まる: {
    reading: "ふかまる",
    meaning: "to deepen,to heighten,to intensify",
  },
  不規則: {
    reading: "ふきそく",
    meaning: "irregularity,unsteadiness,disorderly",
  },
  普及: { reading: "ふきゅう", meaning: "diffusion,spread" },
  付近: { reading: "ふきん", meaning: "neighbourhood,vicinity,environs" },
  拭く: { reading: "ふく", meaning: "to wipe,to dry" },
  副詞: { reading: "ふくし", meaning: "adverb" },
  複写: { reading: "ふくしゃ", meaning: "copy,duplicate" },
  複数: { reading: "ふくすう", meaning: "plural,multiple" },
  含める: {
    reading: "ふくめる",
    meaning: "to include,to instruct,to make one understand",
  },
  膨らます: {
    reading: "ふくらます",
    meaning: "to swell,to expand,to inflate,to bulge",
  },
  膨らむ: {
    reading: "ふくらむ",
    meaning: "to expand,to swell (out),to get big,to become inflated",
  },
  不潔: { reading: "ふけつ", meaning: "unclean,dirty,filthy,impure" },
  更ける: { reading: "ふける", meaning: "to get late,to advance,to wear on" },
  符号: { reading: "ふごう", meaning: "sign,mark,symbol" },
  夫妻: { reading: "ふさい", meaning: "man and wife,married couple" },
  塞がる: { reading: "ふさがる", meaning: "to be plugged up,to be shut up" },
  塞ぐ: { reading: "ふさぐ", meaning: "to stop up,to close up,to block (up)" },
  無沙汰: { reading: "ぶさた", meaning: "neglecting to stay in contact" },
  武士: { reading: "ぶし", meaning: "warrior,samurai" },
  部首: { reading: "ぶしゅ", meaning: "radical (of a kanji character)" },
  襖: { reading: "ふすま", meaning: "sliding screen" },
  附属: { reading: "ふぞく", meaning: "attached,belonging,affiliated" },
  蓋: { reading: "ふた", meaning: "cover,lid,cap" },
  不通: {
    reading: "ふつう",
    meaning: "suspension,interruption,stoppage,tie-up,cessation",
  },
  物騒: { reading: "ぶっそう", meaning: "dangerous,disturbed,insecure" },
  船便: { reading: "ふなびん", meaning: "surface mail (ship)" },
  部品: { reading: "ぶひん", meaning: "parts,accessories" },
  吹雪: { reading: "ふぶき", meaning: "snow storm" },
  父母: { reading: "ふぼ", meaning: "father and mother,parents" },
  踏切: {
    reading: "ふみきり",
    meaning: "railway crossing,level crossing,starting line,scratch,crossover",
  },
  麓: {
    reading: "ふもと",
    meaning: "the foot,the bottom,the base (of a mountain)",
  },
  増やす: { reading: "ふやす", meaning: "to increase,to add to,to augment" },
  殖やす: { reading: "ふやす", meaning: "to increase,to add to,to augment" },
  振舞う: {
    reading: "ふるまう",
    meaning: "to behave,to conduct oneself,to entertain (vt)",
  },
  風呂敷: { reading: "ふろしき", meaning: "wrapping cloth,cloth wrapper" },
  噴火: { reading: "ふんか", meaning: "eruption" },
  分解: { reading: "ぶんかい", meaning: "analysis,disassembly" },
  文芸: {
    reading: "ぶんげい",
    meaning: "literature,art and literature,belles-lettres",
  },
  文献: { reading: "ぶんけん", meaning: "literature,books (reference)" },
  噴水: { reading: "ふんすい", meaning: "water fountain" },
  分数: { reading: "ぶんすう", meaning: "fraction (in math)" },
  文体: { reading: "ぶんたい", meaning: "literary style" },
  分布: { reading: "ぶんぷ", meaning: "distribution" },
  文房具: { reading: "ぶんぼうぐ", meaning: "stationery" },
  文脈: { reading: "ぶんみゃく", meaning: "context" },
  分量: { reading: "ぶんりょう", meaning: "amount,quantity" },
  分類: { reading: "ぶんるい", meaning: "classification" },
  閉会: { reading: "へいかい", meaning: "closure" },
  平気: { reading: "へいき", meaning: "coolness,calmness,composure,unconcern" },
  並行: {
    reading: "へいこう",
    meaning: "(going) side by side,concurrent,abreast,at the same time",
  },
  平日: { reading: "へいじつ", meaning: "weekday,ordinary days" },
  兵隊: { reading: "へいたい", meaning: "soldier,sailor" },
  平凡: {
    reading: "へいぼん",
    meaning: "common,commonplace,ordinary,mediocre",
  },
  平野: { reading: "へいや", meaning: "plain,open field" },
  凹む: {
    reading: "へこむ",
    meaning:
      "to be dented,to be indented,to yield to,to give,to sink,to collapse,to cave in,to be snubbed",
  },
  隔てる: { reading: "へだてる", meaning: "to be shut out" },
  別荘: { reading: "べっそう", meaning: "holiday house,villa" },
  別々: { reading: "べつべつ", meaning: "separately,individually" },
  編集: {
    reading: "へんしゅう",
    meaning: "editing,compilation,editorial (e.g. committee)",
  },
  便所: {
    reading: "べんじょ",
    meaning: "toilet,lavatory,rest room,latrine,comfort station",
  },
  望遠鏡: { reading: "ぼうえんきょう", meaning: "telescope" },
  方角: { reading: "ほうがく", meaning: "direction,way,compass point" },
  箒: { reading: "ほうき", meaning: "(n) broom" },
  方言: { reading: "ほうげん", meaning: "dialect" },
  坊さん: { reading: "ぼうさん", meaning: "Buddhist priest,monk" },
  防止: { reading: "ぼうし", meaning: "prevention,check" },
  方針: { reading: "ほうしん", meaning: "objective,plan,policy" },
  包装: { reading: "ほうそう", meaning: "packing,wrapping" },
  法則: { reading: "ほうそく", meaning: "law,rule" },
  包帯: { reading: "ほうたい", meaning: "bandage,dressing" },
  膨大: {
    reading: "ぼうだい",
    meaning: "huge,bulky,enormous,extensive,swelling,expansion",
  },
  庖丁: { reading: "ほうちょう", meaning: "kitchen knife,carving knife" },
  方程式: { reading: "ほうていしき", meaning: "equation" },
  防犯: { reading: "ぼうはん", meaning: "prevention of crime" },
  方面: {
    reading: "ほうめん",
    meaning: "direction,district,field (e.g., of study)",
  },
  坊や: { reading: "ぼうや", meaning: "boy" },
  放る: { reading: "ほうる", meaning: "to let go" },
  朗らか: { reading: "ほがらか", meaning: "brightness,cheerfulness,melodious" },
  牧場: {
    reading: "ぼくじょう",
    meaning: "(1) farm (livestock),(2) pasture land,meadow,grazing land",
  },
  牧畜: { reading: "ぼくちく", meaning: "stock-farming" },
  保健: {
    reading: "ほけん",
    meaning: "health preservation,hygiene,sanitation",
  },
  募集: { reading: "ぼしゅう", meaning: "recruiting,taking applications" },
  干す: {
    reading: "ほす",
    meaning: "to air,to dry,to desiccate,to drain (off),to drink up",
  },
  北極: { reading: "ほっきょく", meaning: "North Pole" },
  坊っちゃん: { reading: "ぼっちゃん", meaning: "son (of others)" },
  堀: { reading: "ほり", meaning: "moat,canal" },
  掘る: { reading: "ほる", meaning: "to dig,to excavate" },
  彫る: {
    reading: "ほる",
    meaning: "to carve,to engrave,to sculpture,to chisel",
  },
  盆: {
    reading: "ぼん",
    meaning: "Lantern Festival,Festival of the Dead,tray",
  },
  盆地: { reading: "ぼんち", meaning: "basin (e.g. between mountains)" },
  本部: { reading: "ほんぶ", meaning: "headquarters" },
  本来: { reading: "ほんらい", meaning: "essentially,naturally,by nature" },
  枚数: { reading: "まいすう", meaning: "the number of flat things" },
  毎度: {
    reading: "まいど",
    meaning: "each time,common service-sector greeting",
  },
  巻く: { reading: "まく", meaning: "to wind,to coil,to roll" },
  蒔く: { reading: "まく", meaning: "to sow (seeds)" },
  撒く: { reading: "まく", meaning: "to scatter,to sprinkle,to sow" },
  枕: { reading: "まくら", meaning: "pillow,bolster" },
  曲げる: { reading: "まげる", meaning: "to bend,to crook,to lean" },
  摩擦: { reading: "まさつ", meaning: "friction,rubbing,rubdown,chafe" },
  混ざる: {
    reading: "まざる",
    meaning:
      "to be mixed,to be blended with,to associate with,to mingle with,to join",
  },
  交ざる: {
    reading: "まざる",
    meaning:
      "to be mixed,to be blended with,to associate with,to mingle with,to join",
  },
  混じる: {
    reading: "まじる",
    meaning: "to be mixed,to be blended with,to associate with",
  },
  交じる: {
    reading: "まじる",
    meaning: "to be mixed,to be blended with,to associate with",
  },
  混ぜる: { reading: "まぜる", meaning: "to mix,to stir" },
  交ぜる: { reading: "まぜる", meaning: "to be mixed,to be blended with" },
  又は: { reading: "または", meaning: "or,otherwise" },
  待合室: { reading: "まちあいしつ", meaning: "waiting room" },
  待ち合わせる: {
    reading: "まちあわせる",
    meaning: "to rendezvous,to meet at a prearranged place and time",
  },
  街角: { reading: "まちかど", meaning: "street corner" },
  真っ暗: {
    reading: "まっくら",
    meaning: "total darkness,shortsightedness,pitch dark",
  },
  真っ黒: { reading: "まっくろ", meaning: "pitch black" },
  真っ青: { reading: "まっさお", meaning: "deep blue,ghastly pale" },
  真っ先: { reading: "まっさき", meaning: "the head,the foremost,beginning" },
  真っ白: { reading: "まっしろ", meaning: "pure white" },
  祭る: { reading: "まつる", meaning: "to deify,to enshrine" },
  窓口: { reading: "まどぐち", meaning: "ticket window" },
  纏まる: {
    reading: "まとまる",
    meaning: "to be collected,to be settled,to be in order",
  },
  纏める: {
    reading: "まとめる",
    meaning: "to put in order,to collect,to bring to a conclusion",
  },
  真似る: { reading: "まねる", meaning: "to mimic,to imitate" },
  間も無く: {
    reading: "まもなく",
    meaning: "soon,before long,in a short time",
  },
  円い: { reading: "まるい", meaning: "round,circular,spherical" },
  稀: { reading: "まれ", meaning: "rare,seldom" },
  回り道: { reading: "まわりみち", meaning: "detour" },
  満員: { reading: "まんいん", meaning: "full house,no vacancy,sold out" },
  満点: { reading: "まんてん", meaning: "perfect score" },
  見送る: {
    reading: "みおくる",
    meaning: "(1) to see off,to farewell,(2) to escort,(3) to let pass",
  },
  見下ろす: {
    reading: "みおろす",
    meaning: "to overlook,to command a view of,to look down on something",
  },
  見掛け: { reading: "みかけ", meaning: "outward appearance" },
  三日月: { reading: "みかづき", meaning: "new moon,crescent moon" },
  岬: { reading: "みさき", meaning: "cape (on coast)" },
  店屋: { reading: "みせや", meaning: "store,shop" },
  見出し: { reading: "みだし", meaning: "heading,caption,subtitle,index" },
  道順: { reading: "みちじゅん", meaning: "itinerary,route" },
  見付かる: { reading: "みつかる", meaning: "to be found,to be discovered" },
  見付ける: {
    reading: "みつける",
    meaning: "to be familiar,to discover,to detect",
  },
  見直す: {
    reading: "みなおす",
    meaning: "to look again,to get a better opinion of",
  },
  見慣れる: {
    reading: "みなれる",
    meaning: "to become used to seeing,to be familiar with",
  },
  醜い: { reading: "みにくい", meaning: "ugly" },
  実る: { reading: "みのる", meaning: "to bear fruit,to ripen" },
  身分: { reading: "みぶん", meaning: "social position,social status" },
  見本: { reading: "みほん", meaning: "sample" },
  見舞う: { reading: "みまう", meaning: "to ask after (health),to visit" },
  未満: { reading: "みまん", meaning: "less than,insufficient" },
  名字: { reading: "みょうじ", meaning: "surname,family name" },
  ミリ: { reading: "（メートル）", meaning: "milli-,10^-3" },
  診る: { reading: "みる", meaning: "to examine (medical)" },
  民間: {
    reading: "みんかん",
    meaning: "private,civilian,civil,popular,folk,unofficial",
  },
  民謡: { reading: "みんよう", meaning: "folk song,popular song" },
  向う: { reading: "むかう", meaning: "(v5u) to face,to go towards" },
  剥く: { reading: "むく", meaning: "to peel,to skin,to pare,to hull" },
  無限: { reading: "むげん", meaning: "infinite" },
  無地: { reading: "むじ", meaning: "plain,unfigured" },
  蒸し暑い: { reading: "むしあつい", meaning: "humid,sultry" },
  矛盾: { reading: "むじゅん", meaning: "contradiction,inconsistency" },
  蒸す: { reading: "むす", meaning: "to steam,to poultice,to be sultry" },
  無数: { reading: "むすう", meaning: "countless number,infinite number" },
  紫: { reading: "むらさき", meaning: "purple colour,violet" },
  群れ: { reading: "むれ", meaning: "group,crowd,flock,herd" },
  姪: { reading: "めい", meaning: "niece" },
  名作: { reading: "めいさく", meaning: "masterpiece" },
  名刺: { reading: "めいし", meaning: "business card" },
  名詞: { reading: "めいし", meaning: "noun" },
  名所: { reading: "めいしょ", meaning: "famous place" },
  命ずる: { reading: "めいずる", meaning: "to command,to appoint" },
  迷信: { reading: "めいしん", meaning: "superstition" },
  名物: {
    reading: "めいぶつ",
    meaning: "famous product,special product,speciality",
  },
  銘々: { reading: "めいめい", meaning: "each,individual" },
  目上: { reading: "めうえ", meaning: "superior(s),senior" },
  恵まれる: {
    reading: "めぐまれる",
    meaning: "to be blessed with,to be rich in",
  },
  巡る: { reading: "めぐる", meaning: "to go around" },
  目指す: { reading: "めざす", meaning: "to aim at,to have an eye on" },
  目覚し: { reading: "めざまし", meaning: "(abbr) alarm-clock" },
  目下: { reading: "めした", meaning: "at present,now" },
  目印: { reading: "めじるし", meaning: "mark,sign,landmark" },
  目立つ: { reading: "めだつ", meaning: "to be conspicuous,to stand out" },
  目安: { reading: "めやす", meaning: "criterion,aim" },
  免税: { reading: "めんぜい", meaning: "tax exemption,duty exemption" },
  面積: { reading: "めんせき", meaning: "area" },
  面接: { reading: "めんせつ", meaning: "interview" },
  面倒臭い: { reading: "めんどうくさい", meaning: "bother to do,tiresome" },
  儲かる: {
    reading: "もうかる",
    meaning: "to be profitable,to yield a profit",
  },
  儲ける: {
    reading: "もうける",
    meaning: "to get,to earn,to gain,to have (bear, beget) a child",
  },
  申し訳ない: { reading: "もうしわけない", meaning: "inexcusable" },
  木材: { reading: "もくざい", meaning: "lumber,timber,wood" },
  目次: { reading: "もくじ", meaning: "table of contents" },
  潜る: {
    reading: "もぐる",
    meaning:
      "(1) to drive,to pass through,(2) to evade,to hide,(3) to dive (into or under water),to go undergroun",
  },
  餅: { reading: "もち", meaning: "sticky rice cake" },
  元々: { reading: "もともと", meaning: "originally,by nature,from the start" },
  物置: { reading: "ものおき", meaning: "storage room" },
  物語る: { reading: "ものがたる", meaning: "to tell,to indicate" },
  物差し: { reading: "ものさし", meaning: "ruler,measure" },
  物凄い: {
    reading: "ものすごい",
    meaning: "earth-shattering,staggering,to a very great extent",
  },
  紅葉: { reading: "もみじ", meaning: "(1) (Japanese) maple" },
  揉む: { reading: "もむ", meaning: "to rub,to crumple (up),to wrinkle" },
  燃やす: { reading: "もやす", meaning: "to burn" },
  催し: { reading: "もよおし", meaning: "event,festivities,function" },
  盛る: {
    reading: "もる",
    meaning: "(1) to serve (food, etc.),(2) to fill up,(3) to prescribe",
  },
  問答: { reading: "もんどう", meaning: "questions and answers,dialogue" },
  夜間: { reading: "やかん", meaning: "at night,nighttime" },
  薬缶: { reading: "やかん", meaning: "kettle" },
  役者: { reading: "やくしゃ", meaning: "actor,actress" },
  役所: { reading: "やくしょ", meaning: "government office,public office" },
  訳す: { reading: "やくす", meaning: "to translate" },
  役人: { reading: "やくにん", meaning: "government official" },
  薬品: { reading: "やくひん", meaning: "medicine(s),chemical(s)" },
  役目: { reading: "やくめ", meaning: "duty,business" },
  火傷: { reading: "やけど", meaning: "burn,scald" },
  夜行: {
    reading: "やこう",
    meaning: "walking around at night,night train,night travel",
  },
  矢印: { reading: "やじるし", meaning: "directing arrow" },
  薬局: { reading: "やっきょく", meaning: "pharmacy,drugstore" },
  家主: { reading: "やぬし", meaning: "landlord" },
  破れる: { reading: "やぶれる", meaning: "to get torn,to wear out" },
  軟らかい: { reading: "やわらかい", meaning: "soft,tender,limp" },
  遊園地: { reading: "ゆうえんち", meaning: "amusement park" },
  夕刊: { reading: "ゆうかん", meaning: "evening paper" },
  友好: { reading: "ゆうこう", meaning: "friendship" },
  郵送: { reading: "ゆうそう", meaning: "mailing" },
  夕立: { reading: "ゆうだち", meaning: "(sudden) evening shower (rain)" },
  夕日: { reading: "ゆうひ", meaning: "(in) the evening sun,setting sun" },
  悠々: { reading: "ゆうゆう", meaning: "quiet,calm,leisurely" },
  有料: { reading: "ゆうりょう", meaning: "admission-paid,toll" },
  浴衣: {
    reading: "ゆかた",
    meaning: "bathrobe,informal summer kimono,yukata",
  },
  湯気: { reading: "ゆげ", meaning: "steam,vapour" },
  輸血: { reading: "ゆけつ", meaning: "blood transfusion" },
  輸送: { reading: "ゆそう", meaning: "transport,transportation" },
  油断: { reading: "ゆだん", meaning: "negligence,unpreparedness" },
  湯飲み: { reading: "ゆのみ", meaning: "teacup" },
  緩い: { reading: "ゆるい", meaning: "loose,lenient,slow" },
  溶岩: { reading: "ようがん", meaning: "lava" },
  容器: { reading: "ようき", meaning: "container,vessel" },
  用語: { reading: "ようご", meaning: "term,terminology" },
  要旨: { reading: "ようし", meaning: "gist,essentials,summary,fundamentals" },
  幼児: { reading: "ようじ", meaning: "infant,baby,child" },
  容積: { reading: "ようせき", meaning: "capacity,volume" },
  幼稚: { reading: "ようち", meaning: "infancy,childish,infantile" },
  幼稚園: { reading: "ようちえん", meaning: "kindergarten" },
  用途: { reading: "ようと", meaning: "use,usefulness" },
  洋品店: {
    reading: "ようひんてん",
    meaning: "shop which handles Western-style apparel and accessories",
  },
  養分: { reading: "ようぶん", meaning: "nourishment,nutrient" },
  羊毛: { reading: "ようもう", meaning: "wool" },
  漸く: { reading: "ようやく", meaning: "gradually,finally,hardly" },
  要領: { reading: "ようりょう", meaning: "point,gist,essentials,outline" },
  欲張り: { reading: "よくばり", meaning: "avarice,covetousness,greed" },
  余計: {
    reading: "よけい",
    meaning: "too much,unnecessary,abundance,surplus,excess,superfluity",
  },
  汚す: {
    reading: "よごす",
    meaning:
      "(1) to disgrace,to dishonour,(2) to pollute,to contaminate,to soil,to make dirty,to stain",
  },
  寄せる: {
    reading: "よせる",
    meaning: "to collect,to gather,to add,to put aside",
  },
  余所: {
    reading: "よそ",
    meaning: "another place,somewhere else,strange parts",
  },
  四つ角: { reading: "よつかど", meaning: "four corners,crossroads" },
  酔っ払い: { reading: "よっぱらい", meaning: "drunkard" },
  予備: { reading: "よび", meaning: "SPARE" },
  呼び掛ける: {
    reading: "よびかける",
    meaning: "to call out to,to accost,to address (crowd),to appeal",
  },
  呼び出す: { reading: "よびだす", meaning: "to summon,to call (e.g. phone)" },
  蘇る: {
    reading: "よみがえる",
    meaning:
      "to be resurrected,to be revived,to be resuscitated,to be rehabilitated",
  },
  因る: { reading: "よる", meaning: "to come from" },
  慶び: {
    reading: "よろこび",
    meaning:
      "(n) (a) joy,(a) delight,rapture,pleasure,gratification,rejoicing,congratulations,felicitations",
  },
  来日: {
    reading: "らいにち",
    meaning: "arrival in Japan,coming to Japan,visit to Japan",
  },
  落第: { reading: "らくだい", meaning: "failure,dropping out of a class" },
  欄: { reading: "らん", meaning: "column of text (e.g. as in a newspaper)" },
  乱暴: {
    reading: "らんぼう",
    meaning: "rude,violent,rough,lawless,unreasonable,reckless",
  },
  理科: { reading: "りか", meaning: "science" },
  利害: { reading: "りがい", meaning: "advantages and disadvantages,interest" },
  略す: { reading: "りゃくす", meaning: "to abbreviate" },
  流域: { reading: "りゅういき", meaning: "(river) basin" },
  寮: { reading: "りょう", meaning: "hostel,dormitory" },
  両側: { reading: "りょうがわ", meaning: "both sides" },
  漁師: { reading: "りょうし", meaning: "fisherman" },
  領事: { reading: "りょうじ", meaning: "consul" },
  領収: { reading: "りょうしゅう", meaning: "receipt,voucher" },
  臨時: { reading: "りんじ", meaning: "temporary,special,extraordinary" },
  留守番: {
    reading: "るすばん",
    meaning: "care-taking,caretaker,house-watching",
  },
  例外: { reading: "れいがい", meaning: "exception" },
  零点: { reading: "れいてん", meaning: "zero,no marks" },
  冷凍: { reading: "れいとう", meaning: "freezing,cold storage,refrigeration" },
  列島: { reading: "れっとう", meaning: "chain of islands" },
  煉瓦: { reading: "れんが", meaning: "brick" },
  連合: { reading: "れんごう", meaning: "union,alliance" },
  蝋燭: { reading: "ろうそく", meaning: "candle" },
  録音: { reading: "ろくおん", meaning: "(audio) recording" },
  論ずる: { reading: "ろんずる", meaning: "to argue,to discuss,to debate" },
  和英: { reading: "わえい", meaning: "Japanese-English" },
  分る: { reading: "わかる", meaning: "to be understood" },
  分かれる: {
    reading: "わかれる",
    meaning:
      "to branch off,to diverge from,to fork,to split,to dispense,to scatter,to divide into",
  },
  若々しい: { reading: "わかわかしい", meaning: "youthful,young" },
  湧く: {
    reading: "わく",
    meaning: "to boil,to grow hot,to get excited,to gush forth",
  },
  詫びる: { reading: "わびる", meaning: "to apologize" },
  和服: { reading: "わふく", meaning: "Japanese clothes" },
  割算: { reading: "わりざん", meaning: "division (math)" },
  割と: { reading: "わりと", meaning: "relatively, comparitively" },
  割引: { reading: "わりびき", meaning: "discount,reduction,rebate" },
  椀: { reading: "わん", meaning: "Japanese soup bowl,wooden bowl" },
  碗: { reading: "わん", meaning: "bowl" },
};
