export const n4 = {
  間: { reading: "あいだ", meaning: "a space" },
  合う: { reading: "あう", meaning: "to match" },
  上る: { reading: "あがる", meaning: "to rise" },
  赤ん坊: { reading: "あかんぼう", meaning: "baby" },
  空く: { reading: "あく", meaning: "to open, to become empty" },
  浅い: { reading: "あさい", meaning: "shallow, superficial" },
  味: { reading: "あじ", meaning: "flavour" },
  明日: { reading: "あす", meaning: "tomorrow" },
  遊び: { reading: "あそび", meaning: "play" },
  集る: { reading: "あつまる", meaning: "to gather" },
  集める: { reading: "あつめる", meaning: "to collect something" },
  謝る: { reading: "あやまる", meaning: "to apologize" },
  安心: { reading: "あんしん", meaning: "relief" },
  安全: { reading: "あんぜん", meaning: "safety" },
  案内: { reading: "あんない・する", meaning: "to guide" },
  以下: { reading: "いか", meaning: "less than" },
  以外: { reading: "いがい", meaning: "with the exception of" },
  医学: { reading: "いがく", meaning: "medical science" },
  生きる: { reading: "いきる", meaning: "to live" },
  意見: { reading: "いけん", meaning: "opinion" },
  石: { reading: "いし", meaning: "stone" },
  以上: { reading: "いじょう", meaning: "more than, this is all" },
  急ぐ: { reading: "いそぐ", meaning: "to hurry" },
  致す: { reading: "いたす", meaning: "(humble) to do" },
  一度: { reading: "いちど", meaning: "once" },
  一生懸命: { reading: "いっしょうけんめい", meaning: "with utmost effort" },
  糸: { reading: "いと", meaning: "thread" },
  以内: { reading: "いない", meaning: "within" },
  田舎: { reading: "いなか", meaning: "countryside" },
  祈る: { reading: "いのる", meaning: "to pray" },
  植える: { reading: "うえる", meaning: "to plant, to grow" },
  受付: { reading: "うけつけ", meaning: "receiption" },
  受ける: { reading: "うける", meaning: "to take a lesson or test" },
  動く: { reading: "うごく", meaning: "to move" },
  打つ: { reading: "うつ", meaning: "to hit" },
  美しい: { reading: "うつくしい", meaning: "beautiful" },
  写す: { reading: "うつす", meaning: "to copy or photograph" },
  移る: { reading: "うつる", meaning: "to move house or transfer" },
  腕: { reading: "うで", meaning: "arm" },
  裏: { reading: "うら", meaning: "reverse side" },
  売り場: { reading: "うりば", meaning: "place where things are sold" },
  運転: { reading: "うんてん・する", meaning: "to drive" },
  運転手: { reading: "うんてんしゅ", meaning: "driver" },
  運動: { reading: "うんどう・する", meaning: "to exercise" },
  枝: { reading: "えだ", meaning: "branch, twig" },
  選ぶ: { reading: "えらぶ", meaning: "to choose" },
  遠慮: {
    reading: "えんりょ・する",
    meaning: "to be reserved, to be restrained",
  },
  お祝い: { reading: "おいわい", meaning: "congratulation" },
  億: { reading: "おく", meaning: "one hundred million" },
  屋上: { reading: "おくじょう", meaning: "rooftop" },
  贈り物: { reading: "おくりもの", meaning: "gift" },
  送る: { reading: "おくる", meaning: "to send" },
  遅れる: { reading: "おくれる", meaning: "to be late" },
  起す: { reading: "おこす", meaning: "to wake" },
  行う: { reading: "おこなう", meaning: "to do" },
  怒る: { reading: "おこる", meaning: "to get angry, to be angry" },
  押し入れ: { reading: "おしいれ", meaning: "closet" },
  お嬢さん: { reading: "おじょうさん", meaning: "young lady" },
  お宅: { reading: "おたく", meaning: "(polite) your house" },
  落る: { reading: "おちる", meaning: "to fall or drop" },
  夫: { reading: "おっと", meaning: "husband" },
  音: { reading: "おと", meaning: "sound, note" },
  落す: { reading: "おとす", meaning: "to drop" },
  踊り: { reading: "おどり", meaning: "a dance" },
  踊る: { reading: "おどる", meaning: "to dance" },
  驚く: { reading: "おどろく", meaning: "to be surprised" },
  お祭り: { reading: "おまつり", meaning: "festival" },
  お見舞い: {
    reading: "おみまい",
    meaning: "calling on someone who is ill, enquiry",
  },
  お土産: { reading: "おみやげ", meaning: "souvenir" },
  思い出す: { reading: "おもいだす", meaning: "to remember" },
  思う: { reading: "おもう", meaning: "to think, to feel" },
  表: { reading: "おもて", meaning: "the front" },
  親: { reading: "おや", meaning: "parents" },
  下りる: { reading: "おりる", meaning: "to get off" },
  折る: { reading: "おる", meaning: "to break or to fold" },
  お礼: { reading: "おれい", meaning: "expression of gratitude" },
  折れる: { reading: "おれる", meaning: "to break or be folded" },
  終わり: { reading: "おわり", meaning: "the end" },
  海岸: { reading: "かいがん", meaning: "coast" },
  会議: { reading: "かいぎ", meaning: "meeting" },
  会議室: { reading: "かいぎしつ", meaning: "meeting room" },
  会場: { reading: "かいじょう", meaning: "assembly hall or meeting place" },
  会話: { reading: "かいわ", meaning: "conversation" },
  帰り: { reading: "かえり", meaning: "return" },
  変える: { reading: "かえる", meaning: "to change" },
  科学: { reading: "かがく", meaning: "science" },
  鏡: { reading: "かがみ", meaning: "mirror" },
  掛ける: { reading: "かける", meaning: "to hang something" },
  飾る: { reading: "かざる", meaning: "to decorate" },
  火事: { reading: "かじ", meaning: "fire" },
  "堅/硬/固い": { reading: "かたい", meaning: "hard" },
  形: { reading: "かたち", meaning: "shape" },
  片付ける: { reading: "かたづける", meaning: "to tidy up" },
  課長: { reading: "かちょう", meaning: "section manager" },
  勝つ: { reading: "かつ", meaning: "to win" },
  家内: { reading: "かない", meaning: "housewife" },
  悲しい: { reading: "かなしい", meaning: "sad" },
  必ず: { reading: "かならず", meaning: "certainly, necessarily" },
  "お・金持ち": { reading: "かねもち/おかねもち", meaning: "rich man" },
  彼女: { reading: "かのじょ", meaning: "she, girlfriend" },
  壁: { reading: "かべ", meaning: "wall" },
  髪: { reading: "かみ", meaning: "hair" },
  噛む: { reading: "かむ", meaning: "to bite, to chew" },
  通う: { reading: "かよう", meaning: "to commute" },
  彼: { reading: "かれ", meaning: "he, boyfriend" },
  彼ら: { reading: "かれら", meaning: "they" },
  乾く: { reading: "かわく", meaning: "to get dry" },
  代わり: { reading: "かわり", meaning: "substitute, alternate" },
  変わる: { reading: "かわる", meaning: "to change" },
  考える: { reading: "かんがえる", meaning: "to consider" },
  関係: { reading: "かんけい", meaning: "relationship" },
  看護婦: { reading: "かんごふ", meaning: "female nurse" },
  簡単: { reading: "かんたん", meaning: "simple" },
  気: { reading: "き", meaning: "spirit, mood" },
  機会: { reading: "きかい", meaning: "opportunity" },
  危険: { reading: "きけん", meaning: "danger" },
  聞こえる: { reading: "きこえる", meaning: "to be heard" },
  汽車: { reading: "きしゃ", meaning: "steam train" },
  技術: { reading: "ぎじゅつ", meaning: "art, technology, skill" },
  季節: { reading: "きせつ", meaning: "season" },
  規則: { reading: "きそく", meaning: "regulations" },
  絹: { reading: "きぬ", meaning: "silk" },
  厳しい: { reading: "きびしい", meaning: "strict" },
  気分: { reading: "きぶん", meaning: "mood" },
  決る: { reading: "きまる", meaning: "to be decided" },
  君: {
    reading: "きみ",
    meaning: "(informal) You (used by men towards women)",
  },
  決める: { reading: "きめる", meaning: "to decide" },
  気持ち: { reading: "きもち", meaning: "feeling, mood" },
  着物: { reading: "きもの", meaning: "kimono" },
  客: { reading: "きゃく", meaning: "guest, customer" },
  急: { reading: "きゅう", meaning: "urgent, steep" },
  急行: { reading: "きゅうこう", meaning: "speedy, express" },
  教育: { reading: "きょういく", meaning: "education" },
  教会: { reading: "きょうかい", meaning: "church" },
  競争: { reading: "きょうそう", meaning: "competition" },
  興味: { reading: "きょうみ", meaning: "an interest" },
  近所: { reading: "きんじょ", meaning: "neighbourhood" },
  具合: { reading: "ぐあい", meaning: "condition, health" },
  空気: { reading: "くうき", meaning: "air, atmosphere" },
  空港: { reading: "くうこう", meaning: "airport" },
  草: { reading: "くさ", meaning: "grass" },
  首: { reading: "くび", meaning: "neck" },
  雲: { reading: "くも", meaning: "cloud" },
  比べる: { reading: "くらべる", meaning: "to compare" },
  暮れる: { reading: "くれる", meaning: "to get dark, to come to an end" },
  君: { reading: "くん", meaning: "suffix for familiar young male" },
  毛: { reading: "け", meaning: "hair or fur" },
  計画: { reading: "けいかく・する", meaning: "to plan" },
  経験: { reading: "けいけん・する", meaning: "to experience" },
  経済: { reading: "けいざい", meaning: "finance, economy" },
  警察: { reading: "けいさつ", meaning: "police" },
  景色: { reading: "けしき", meaning: "scene, landscape" },
  消しゴム: { reading: "けしゴム", meaning: "eraser" },
  下宿: { reading: "げしゅく", meaning: "lodging" },
  決して: { reading: "けっして", meaning: "never" },
  原因: { reading: "げんいん", meaning: "cause, source" },
  研究: { reading: "けんきゅう", meaning: "research" },
  研究室: { reading: "けんきゅうしつ", meaning: "study room, laboratory" },
  見物: { reading: "けんぶつ", meaning: "sightseeing" },
  子: { reading: "こ", meaning: "child" },
  郊外: { reading: "こうがい", meaning: "outskirts" },
  講義: { reading: "こうぎ", meaning: "lecture" },
  工業: { reading: "こうぎょう", meaning: "the manufacturing industry" },
  高校: { reading: "こうこう", meaning: "high school" },
  高校生: { reading: "こうこうせい", meaning: "high school student" },
  工場: { reading: "こうじょう", meaning: "factory" },
  校長: { reading: "こうちょう", meaning: "headmaster" },
  交通: { reading: "こうつう", meaning: "traffic, transportation" },
  講堂: { reading: "こうどう", meaning: "auditorium" },
  高等学校: { reading: "こうとうがっこう", meaning: "high school" },
  公務員: { reading: "こうむいん", meaning: "government worker" },
  国際: { reading: "こくさい", meaning: "international" },
  心: { reading: "こころ", meaning: "core, heart" },
  御主人: { reading: "ごしゅじん", meaning: "(honorable) your husband" },
  故障: { reading: "こしょう・する", meaning: "to break-down" },
  ご存じ: { reading: "ごぞんじ", meaning: "knowing, acquaintance" },
  答: { reading: "こたえ", meaning: "response" },
  小鳥: { reading: "ことり", meaning: "small bird" },
  細かい: { reading: "こまかい", meaning: "small, fine" },
  込む: { reading: "こむ", meaning: "to be crowded" },
  米: { reading: "こめ", meaning: "uncooked rice" },
  怖い: { reading: "こわい", meaning: "frightening" },
  壊す: { reading: "こわす", meaning: "to break" },
  壊れる: { reading: "こわれる", meaning: "to be broken" },
  今度: { reading: "こんど", meaning: "now, next time" },
  今夜: { reading: "こんや", meaning: "tonight" },
  最近: { reading: "さいきん", meaning: "latest, nowadays" },
  最後: { reading: "さいご", meaning: "last, end" },
  最初: { reading: "さいしょ", meaning: "beginning, first" },
  坂: { reading: "さか", meaning: "slope, hill" },
  探す: { reading: "さがす", meaning: "to look for" },
  下る: { reading: "さがる", meaning: "to get down, to descend" },
  盛ん: { reading: "さかん", meaning: "popularity, prosperous" },
  下げる: { reading: "さげる", meaning: "to hang, to lower, to move back" },
  差し上げる: { reading: "さしあげる", meaning: "(polite) to give" },
  寂しい: { reading: "さびしい", meaning: "lonely" },
  さ来月: { reading: "さらいげつ", meaning: "the month after next" },
  さ来週: { reading: "さらいしゅう", meaning: "the week after next" },
  騒ぐ: { reading: "さわぐ", meaning: "to make noise, to be excited" },
  触る: { reading: "さわる", meaning: "to touch" },
  産業: { reading: "さんぎょう", meaning: "industry" },
  残念: { reading: "ざんねん", meaning: "disappointment" },
  市: { reading: "し", meaning: "city" },
  字: { reading: "じ", meaning: "character" },
  試合: { reading: "しあい", meaning: "match, game" },
  仕方: { reading: "しかた", meaning: "method" },
  試験: { reading: "しけん", meaning: "examination" },
  事故: { reading: "じこ", meaning: "accident" },
  地震: { reading: "じしん", meaning: "earthquake" },
  時代: { reading: "じだい", meaning: "era" },
  下着: { reading: "したぎ", meaning: "underwear" },
  支度: { reading: "したく・する", meaning: "to prepare" },
  失敗: { reading: "しっぱい", meaning: "failure, mistake" },
  辞典: { reading: "じてん", meaning: "dictionary" },
  品物: { reading: "しなもの", meaning: "goods" },
  島: { reading: "しま", meaning: "island" },
  市民: { reading: "しみん", meaning: "citizen" },
  事務所: { reading: "じむしょ", meaning: "office" },
  社会: { reading: "しゃかい", meaning: "society, public" },
  社長: { reading: "しゃちょう", meaning: "company president" },
  自由: { reading: "じゆう", meaning: "freedom" },
  習慣: { reading: "しゅうかん", meaning: "custom, manners" },
  住所: { reading: "じゅうしょ", meaning: "an address, a residence" },
  柔道: { reading: "じゅうどう", meaning: "judo" },
  十分: { reading: "じゅうぶん", meaning: "enough" },
  出席: { reading: "しゅっせき・する", meaning: "to attend" },
  出発: { reading: "しゅっぱつ・する", meaning: "to depart" },
  趣味: { reading: "しゅみ", meaning: "hobby" },
  準備: { reading: "じゅんび・する", meaning: "to prepare" },
  紹介: { reading: "しょうかい", meaning: "introduction" },
  小学校: { reading: "しょうがっこう", meaning: "elementary school" },
  小説: { reading: "しょうせつ", meaning: "novel" },
  招待: { reading: "しょうたい・する", meaning: "to invite" },
  承知: { reading: "しょうち・する", meaning: "to consent" },
  将来: { reading: "しょうらい", meaning: "future, prospects" },
  食事: { reading: "しょくじ・する", meaning: "to have a meal" },
  食料品: { reading: "しょくりょうひん", meaning: "groceries" },
  女性: { reading: "じょせい", meaning: "woman" },
  知らせる: { reading: "しらせる", meaning: "to notify" },
  調べる: { reading: "しらべる", meaning: "to investigate" },
  人口: { reading: "じんこう", meaning: "population" },
  神社: { reading: "じんじゃ", meaning: "Shinto shrine" },
  親切: { reading: "しんせつ", meaning: "kindness" },
  心配: { reading: "しんぱい・する", meaning: "to worry" },
  新聞社: { reading: "しんぶんしゃ", meaning: "newspaper company" },
  水泳: { reading: "すいえい", meaning: "swimming" },
  水道: { reading: "すいどう", meaning: "water supply" },
  数学: { reading: "すうがく", meaning: "mathematics, arithmetic" },
  過ぎる: { reading: "すぎる", meaning: "to exceed" },
  凄い: { reading: "すごい", meaning: "terrific" },
  進む: { reading: "すすむ", meaning: "to make progress" },
  捨てる: { reading: "すてる", meaning: "to throw away" },
  砂: { reading: "すな", meaning: "sand" },
  滑る: { reading: "すべる", meaning: "to slide, to slip" },
  隅: { reading: "すみ", meaning: "corner, nook" },
  済む: { reading: "すむ", meaning: "to finish" },
  生活: { reading: "せいかつ・する", meaning: "to live" },
  生産: { reading: "せいさん・する", meaning: "to produce" },
  政治: { reading: "せいじ", meaning: "politics, government" },
  西洋: { reading: "せいよう", meaning: "western countries" },
  世界: { reading: "せかい", meaning: "the world" },
  席: { reading: "せき", meaning: "seat" },
  説明: { reading: "せつめい", meaning: "explanation" },
  背中: { reading: "せなか", meaning: "back of the body" },
  世話: { reading: "せわ・する", meaning: "to look after" },
  線: { reading: "せん", meaning: "line" },
  戦争: { reading: "せんそう", meaning: "war" },
  先輩: { reading: "せんぱい", meaning: "senior" },
  相談: { reading: "そうだん・する", meaning: "to discuss" },
  育てる: { reading: "そだてる", meaning: "to rear, to bring up" },
  卒業: { reading: "そつぎょう", meaning: "graduation" },
  祖父: { reading: "そふ", meaning: "grandfather" },
  祖母: { reading: "そぼ", meaning: "grandmother" },
  退院: { reading: "たいいん・する", meaning: "to leave hospital" },
  大学生: { reading: "だいがくせい", meaning: "university student" },
  大事: { reading: "だいじ", meaning: "important, valuable, serious matter" },
  大体: { reading: "だいたい", meaning: "generally" },
  大分: { reading: "だいぶ", meaning: "greatly" },
  台風: { reading: "たいふう", meaning: "typhoon" },
  倒れる: { reading: "たおれる", meaning: "To fall" },
  確か: { reading: "たしか", meaning: "definite" },
  足す: { reading: "たす", meaning: "to add a number" },
  訪ねる: { reading: "たずねる", meaning: "to visit" },
  尋ねる: { reading: "たずねる", meaning: "to ask" },
  正しい: { reading: "ただしい", meaning: "correct" },
  畳: { reading: "たたみ", meaning: "Japanese straw mat" },
  立てる: { reading: "たてる", meaning: "to stand something up" },
  建てる: { reading: "たてる", meaning: "to build" },
  例えば: { reading: "たとえば", meaning: "for example" },
  棚: { reading: "たな", meaning: "shelves" },
  楽しみ: { reading: "たのしみ", meaning: "joy" },
  楽む: { reading: "たのしむ", meaning: "to enjoy oneself" },
  為: { reading: "ため", meaning: "in order to" },
  足りる: { reading: "たりる", meaning: "to be enough" },
  男性: { reading: "だんせい", meaning: "male" },
  暖房: { reading: "だんぼう", meaning: "heating" },
  血: { reading: "ち", meaning: "blood" },
  力: { reading: "ちから", meaning: "strength, power" },
  注意: { reading: "ちゅうい", meaning: "caution" },
  中学校: {
    reading: "ちゅうがっこう",
    meaning: "junior high school, middle school",
  },
  注射: { reading: "ちゅうしゃ", meaning: "injection" },
  駐車場: { reading: "ちゅうしゃじょう", meaning: "parking lot" },
  地理: { reading: "ちり", meaning: "geography" },
  捕まえる: { reading: "つかまえる", meaning: "to seize" },
  付く: { reading: "つく", meaning: "to be attached" },
  漬ける: { reading: "つける", meaning: "to soak, to pickle" },
  都合: { reading: "つごう", meaning: "circumstances, convenience" },
  伝える: { reading: "つたえる", meaning: "to report" },
  続く: { reading: "つづく", meaning: "to be continued" },
  続ける: { reading: "つづける", meaning: "to continue" },
  包む: { reading: "つつむ", meaning: "to wrap" },
  妻: { reading: "つま", meaning: "(humble) wife" },
  釣る: { reading: "つる", meaning: "to fish" },
  連れる: { reading: "つれる", meaning: "to lead" },
  丁寧: { reading: "ていねい", meaning: "polite" },
  適当: { reading: "てきとう", meaning: "suitability" },
  手伝う: { reading: "てつだう", meaning: "to assist" },
  手袋: { reading: "てぶくろ", meaning: "glove" },
  寺: { reading: "てら", meaning: "temple" },
  点: { reading: "てん", meaning: "point, dot" },
  店員: { reading: "てんいん", meaning: "shop assistant" },
  天気予報: { reading: "てんきよほう", meaning: "weather forecast" },
  電灯: { reading: "でんとう", meaning: "electric light" },
  電報: { reading: "でんぽう", meaning: "telegram" },
  展覧会: { reading: "てんらんかい", meaning: "exhibition" },
  都: { reading: "と", meaning: "metropolitan" },
  道具: { reading: "どうぐ", meaning: "tool, means" },
  動物園: { reading: "どうぶつえん", meaning: "zoo" },
  遠く: { reading: "とおく", meaning: "distant" },
  通る: { reading: "とおる", meaning: "to go through" },
  特に: { reading: "とくに", meaning: "particularly, especially" },
  特別: { reading: "とくべつ", meaning: "special" },
  途中: { reading: "とちゅう", meaning: "on the way" },
  特急: {
    reading: "とっきゅう",
    meaning: "limited express train (faster than an express train)",
  },
  届ける: { reading: "とどける", meaning: "to reach" },
  泊まる: { reading: "とまる", meaning: "to lodge at" },
  止める: { reading: "とめる", meaning: "to stop something" },
  取り替える: { reading: "とりかえる", meaning: "to exchange" },
  泥棒: { reading: "どろぼう", meaning: "thief" },
  直す: { reading: "なおす", meaning: "to fix, to repair" },
  直る: { reading: "なおる", meaning: "to be fixed, to be repaired" },
  治る: { reading: "なおる", meaning: "to be cured, to heal" },
  中々: { reading: "なかなか", meaning: "considerably" },
  泣く: { reading: "なく", meaning: "to weep" },
  無くなる: { reading: "なくなる", meaning: "to disappear, to get lost" },
  亡くなる: { reading: "なくなる", meaning: "to die" },
  投げる: { reading: "なげる", meaning: "to throw or cast away" },
  鳴る: { reading: "なる", meaning: "to sound" },
  慣れる: { reading: "なれる", meaning: "to grow accustomed to" },
  苦い: { reading: "にがい", meaning: "bitter" },
  二階建て: { reading: "にかいだて", meaning: "two storied" },
  逃げる: { reading: "にげる", meaning: "to escape" },
  日記: { reading: "にっき", meaning: "journal" },
  入院: { reading: "にゅういん・する", meaning: "to hospitalise" },
  入学: {
    reading: "にゅうがく・する",
    meaning: "to enter school or university",
  },
  似る: { reading: "にる", meaning: "to be similar" },
  人形: { reading: "にんぎょう", meaning: "doll, figure" },
  盗む: { reading: "ぬすむ", meaning: "to steal" },
  塗る: { reading: "ぬる", meaning: "to paint, to plaster" },
  熱: { reading: "ねつ", meaning: "fever" },
  寝坊: { reading: "ねぼう", meaning: "sleeping in late" },
  眠い: { reading: "ねむい", meaning: "sleepy" },
  眠る: { reading: "ねむる", meaning: "to sleep" },
  残る: { reading: "のこる", meaning: "to remain" },
  乗り換える: {
    reading: "のりかえる",
    meaning: "to change between buses or trains",
  },
  乗り物: { reading: "のりもの", meaning: "vehicle" },
  葉: { reading: "は", meaning: "leaf" },
  場合: { reading: "ばあい", meaning: "situation" },
  倍: { reading: "ばい", meaning: "double" },
  拝見: { reading: "はいけん・する", meaning: "(humble) to look at" },
  歯医者: { reading: "はいしゃ", meaning: "dentist" },
  運ぶ: { reading: "はこぶ", meaning: "to transport" },
  始める: { reading: "はじめる", meaning: "to begin" },
  場所: { reading: "ばしょ", meaning: "location" },
  恥ずかしい: { reading: "はずかしい", meaning: "embarrassed" },
  発音: { reading: "はつおん", meaning: "pronunciation" },
  花見: { reading: "はなみ", meaning: "cherry-blossom viewing" },
  林: { reading: "はやし", meaning: "woods, forester" },
  払う: { reading: "はらう", meaning: "to pay" },
  番組: { reading: "ばんぐみ", meaning: "television or radio program" },
  反対: { reading: "はんたい", meaning: "opposition" },
  日: { reading: "ひ", meaning: "day, sun" },
  火: { reading: "ひ", meaning: "fire" },
  冷える: { reading: "ひえる", meaning: "to grow cold" },
  光: { reading: "ひかり", meaning: "light" },
  光る: { reading: "ひかる", meaning: "to shine, to glitter" },
  引き出し: { reading: "ひきだし", meaning: "drawer, drawing out" },
  引き出す: { reading: "ひきだす", meaning: "to withdraw" },
  飛行場: { reading: "ひこうじょう", meaning: "airport" },
  久しぶり: { reading: "ひさしぶり", meaning: "after a long time" },
  美術館: { reading: "びじゅつかん", meaning: "art gallery" },
  非常に: { reading: "ひじょうに", meaning: "extremely" },
  引っ越す: { reading: "ひっこす", meaning: "to move house" },
  必要: { reading: "ひつよう", meaning: "necessary" },
  開く: { reading: "ひらく", meaning: "to open an event" },
  昼間: { reading: "ひるま", meaning: "daytime, during the day" },
  昼休み: { reading: "ひるやすみ", meaning: "noon break" },
  拾う: { reading: "ひろう", meaning: "to pick up, to gather" },
  増える: { reading: "ふえる", meaning: "to increase" },
  深い: { reading: "ふかい", meaning: "deep" },
  複雑: { reading: "ふくざつ", meaning: "complexity, complication" },
  復習: { reading: "ふくしゅう", meaning: "revision" },
  部長: { reading: "ぶちょう", meaning: "head of a section" },
  普通: {
    reading: "ふつう",
    meaning: "usually, or a train that stops at every station",
  },
  太る: { reading: "ふとる", meaning: "to become fat" },
  布団: { reading: "ふとん", meaning: "Japanese bedding, futon" },
  舟: { reading: "ふね", meaning: "ship" },
  不便: { reading: "ふべん", meaning: "inconvenience" },
  踏む: { reading: "ふむ", meaning: "to step on" },
  降り出す: { reading: "ふりだす", meaning: "to start to rain" },
  文化: { reading: "ぶんか", meaning: "culture" },
  文学: { reading: "ぶんがく", meaning: "literature" },
  文法: { reading: "ぶんぽう", meaning: "grammar" },
  別: { reading: "べつ", meaning: "different" },
  変: { reading: "へん", meaning: "strange" },
  返事: { reading: "へんじ", meaning: "reply" },
  貿易: { reading: "ぼうえき", meaning: "trade" },
  放送: { reading: "ほうそう・する", meaning: "to broadcast" },
  法律: { reading: "ほうりつ", meaning: "law" },
  僕: { reading: "ぼく", meaning: "I (used by males)" },
  星: { reading: "ほし", meaning: "star" },
  翻訳: { reading: "ほんやく", meaning: "translation" },
  参る: { reading: "まいる", meaning: "(humble) to go, to come" },
  負ける: { reading: "まける", meaning: "to lose" },
  間違える: { reading: "まちがえる", meaning: "to make a mistake" },
  間に合う: { reading: "まにあう", meaning: "to be in time for" },
  周り: { reading: "まわり", meaning: "surroundings" },
  回る: { reading: "まわる", meaning: "to go around" },
  漫画: { reading: "まんが", meaning: "comic" },
  真中: { reading: "まんなか", meaning: "middle" },
  見える: { reading: "みえる", meaning: "to be in sight" },
  湖: { reading: "みずうみ", meaning: "lake" },
  味噌: { reading: "みそ", meaning: "bean paste" },
  見つかる: { reading: "みつかる", meaning: "to be discovered" },
  見つける: { reading: "みつける", meaning: "to discover" },
  皆: { reading: "みな", meaning: "everybody" },
  港: { reading: "みなと", meaning: "harbour" },
  向かう: { reading: "むかう", meaning: "to face" },
  迎える: { reading: "むかえる", meaning: "to go out to meet" },
  昔: { reading: "むかし", meaning: "olden days, former" },
  虫: { reading: "むし", meaning: "insect" },
  息子: { reading: "むすこ", meaning: "(humble) son" },
  娘: { reading: "むすめ", meaning: "(humble) daughter" },
  無理: { reading: "むり", meaning: "impossible" },
  召し上がる: { reading: "めしあがる", meaning: "(polite) to eat" },
  珍しい: { reading: "めずらしい", meaning: "rare" },
  申し上げる: { reading: "もうしあげる", meaning: "(humble) to say, to tell" },
  申す: { reading: "もうす", meaning: "(humble) to be called, to say" },
  戻る: { reading: "もどる", meaning: "to turn back" },
  木綿: { reading: "もめん", meaning: "cotton" },
  森: { reading: "もり", meaning: "forest" },
  焼く: { reading: "やく", meaning: "to bake, to grill" },
  約束: { reading: "やくそく", meaning: "promise" },
  役に立つ: { reading: "やくにたつ", meaning: "to be helpful" },
  焼ける: { reading: "やける", meaning: "to burn, to be roasted" },
  優しい: { reading: "やさしい", meaning: "kind" },
  痩せる: { reading: "やせる", meaning: "to become thin" },
  止む: { reading: "やむ", meaning: "to stop" },
  止める: { reading: "やめる", meaning: "to stop" },
  柔らかい: { reading: "やわらかい", meaning: "soft" },
  湯: { reading: "ゆ", meaning: "hot water" },
  輸出: { reading: "ゆしゅつ・する", meaning: "to export" },
  輸入: { reading: "ゆにゅう・する", meaning: "to import" },
  指: { reading: "ゆび", meaning: "finger" },
  指輪: { reading: "ゆびわ", meaning: "finger ring" },
  夢: { reading: "ゆめ", meaning: "dream" },
  揺れる: { reading: "ゆれる", meaning: "to shake, to sway" },
  用: { reading: "よう", meaning: "use" },
  用意: { reading: "ようい", meaning: "preparation" },
  用事: { reading: "ようじ", meaning: "things to do" },
  汚れる: { reading: "よごれる", meaning: "to get dirty" },
  予習: { reading: "よしゅう", meaning: "preparation for a lesson" },
  予定: { reading: "よてい", meaning: "arrangement" },
  予約: { reading: "よやく", meaning: "reservation" },
  寄る: { reading: "よる", meaning: "to visit" },
  喜ぶ: { reading: "よろこぶ", meaning: "to be delighted" },
  理由: { reading: "りゆう", meaning: "reason" },
  利用: { reading: "りよう", meaning: "utilization" },
  両方: { reading: "りょうほう", meaning: "both sides" },
  旅館: { reading: "りょかん", meaning: "Japanese hotel" },
  留守: { reading: "るす", meaning: "absence" },
  冷房: { reading: "れいぼう", meaning: "air conditioning" },
  歴史: { reading: "れきし", meaning: "history" },
  連絡: { reading: "れんらく", meaning: "contact" },
  沸かす: { reading: "わかす", meaning: "to boil, to heat" },
  別れる: { reading: "わかれる", meaning: "to separate" },
  沸く: { reading: "わく", meaning: "to boil, to grow hot, to get excited" },
  訳: { reading: "わけ", meaning: "meaning, reason" },
  忘れ物: { reading: "わすれもの", meaning: "lost article" },
  笑う: { reading: "わらう", meaning: "to laugh, to smile" },
  割合: { reading: "わりあい", meaning: "rate, ratio, percentage" },
  割れる: { reading: "われる", meaning: "to break" },
  泳ぎ方: { reading: "およぎかた", meaning: "way of swimming" },
};
