export const n5 = {
  会う: { reading: "あう", meaning: "to meet" },
  青: { reading: "あお", meaning: "blue" },
  青い: { reading: "あおい", meaning: "blue" },
  赤: { reading: "あか", meaning: "red" },
  赤い: { reading: "あかい", meaning: "red" },
  明い: { reading: "あかるい", meaning: "bright" },
  秋: { reading: "あき", meaning: "autumn" },
  開く: { reading: "あく", meaning: "to open, to become open" },
  開ける: { reading: "あける", meaning: "to open" },
  上げる: { reading: "あげる", meaning: "to give" },
  朝: { reading: "あさ", meaning: "morning" },
  朝御飯: { reading: "あさごはん", meaning: "breakfast" },
  足: { reading: "あし", meaning: "foot, leg" },
  明日: { reading: "あした", meaning: "tomorrow" },
  遊ぶ: { reading: "あそぶ", meaning: "to play, to make a visit" },
  暖かい: { reading: "あたたかい", meaning: "warm" },
  頭: { reading: "あたま", meaning: "head" },
  新しい: { reading: "あたらしい", meaning: "new" },
  暑い: { reading: "あつい", meaning: "hot" },
  熱い: { reading: "あつい", meaning: "hot to the touch" },
  厚い: { reading: "あつい", meaning: "kind, deep, thick" },
  後: { reading: "あと", meaning: "afterwards" },
  兄: { reading: "あに", meaning: "(humble) older brother" },
  姉: { reading: "あね", meaning: "(humble) older sister" },
  危ない: { reading: "あぶない", meaning: "dangerous" },
  甘い: { reading: "あまい", meaning: "sweet" },
  雨: { reading: "あめ", meaning: "rain" },
  飴: { reading: "あめ", meaning: "candy" },
  洗う: { reading: "あらう", meaning: "to wash" },
  歩く: { reading: "あるく", meaning: "to walk" },
  言う: { reading: "いう", meaning: "to say" },
  家: { reading: "いえ", meaning: "house" },
  行く: { reading: "いく", meaning: "to go" },
  池: { reading: "いけ", meaning: "pond" },
  医者: { reading: "いしゃ", meaning: "medical doctor" },
  忙しい: { reading: "いそがしい", meaning: "busy, irritated" },
  痛い: { reading: "いたい", meaning: "painful" },
  一: { reading: "いち", meaning: "one" },
  一日: { reading: "いちにち", meaning: "first of the month" },
  五日: { reading: "いつか", meaning: "five days, fifth day" },
  一緒: { reading: "いっしょ", meaning: "together" },
  五つ: { reading: "いつつ", meaning: "five" },
  犬: { reading: "いぬ", meaning: "dog" },
  今: { reading: "いま", meaning: "now" },
  意味: { reading: "いみ", meaning: "meaning" },
  妹: { reading: "いもうと", meaning: "(humble) younger sister" },
  嫌: { reading: "いや", meaning: "unpleasant" },
  入口: { reading: "いりぐち", meaning: "entrance" },
  居る: {
    reading: "いる",
    meaning: "to be, to have (used for people and animals)",
  },
  要る: { reading: "いる", meaning: "to need" },
  入れる: { reading: "いれる", meaning: "to put in" },
  色: { reading: "いろ", meaning: "colour" },
  上: { reading: "うえ", meaning: "on top of" },
  後ろ: { reading: "うしろ", meaning: "behind" },
  薄い: { reading: "うすい", meaning: "thin, weak" },
  歌: { reading: "うた", meaning: "song" },
  歌う: { reading: "うたう", meaning: "to sing" },
  生まれる: { reading: "うまれる", meaning: "to be born" },
  海: { reading: "うみ", meaning: "sea" },
  売る: { reading: "うる", meaning: "to sell" },
  煩い: { reading: "うるさい", meaning: "noisy, annoying" },
  上着: { reading: "うわぎ", meaning: "jacket" },
  絵: { reading: "え", meaning: "picture" },
  映画: { reading: "えいが", meaning: "movie" },
  映画館: { reading: "えいがかん", meaning: "cinema" },
  英語: { reading: "えいご", meaning: "English language" },
  駅: { reading: "えき", meaning: "station" },
  鉛筆: { reading: "えんぴつ", meaning: "pencil" },
  多い: { reading: "おおい", meaning: "many" },
  大きい: { reading: "おおきい", meaning: "big" },
  大きな: { reading: "おおきな", meaning: "big" },
  大勢: { reading: "おおぜい", meaning: "great number of people" },
  お母さん: { reading: "おかあさん", meaning: "(honorable) mother" },
  お菓子: { reading: "おかし", meaning: "sweets, candy" },
  お金: { reading: "おかね", meaning: "money" },
  起きる: { reading: "おきる", meaning: "to get up" },
  置く: { reading: "おく", meaning: "to put" },
  奥さん: { reading: "おくさん", meaning: "(honorable) wife" },
  お酒: { reading: "おさけ", meaning: "alcohol, rice wine" },
  お皿: { reading: "おさら", meaning: "plate, dish" },
  "伯父/叔父": {
    reading: "おじいさん",
    meaning: "grandfather, male senior citizen",
  },
  教える: { reading: "おしえる", meaning: "to teach, to tell" },
  "伯父/叔父": { reading: "おじさん", meaning: "uncle, middle aged gentleman" },
  押す: { reading: "おす", meaning: "to push, to stamp something" },
  遅い: { reading: "おそい", meaning: "late, slow" },
  お茶: { reading: "おちゃ", meaning: "green tea" },
  お手洗い: { reading: "おてあらい", meaning: "bathroom" },
  お父さん: { reading: "おとうさん", meaning: "(honorable) father" },
  弟: { reading: "おとうと", meaning: "younger brother" },
  男: { reading: "おとこ", meaning: "Man" },
  男の子: { reading: "おとこのこ", meaning: "Boy" },
  一昨日: { reading: "おととい", meaning: "day before yesterday" },
  一昨年: { reading: "おととし", meaning: "year before last" },
  大人: { reading: "おとな", meaning: "Adult" },
  同じ: { reading: "おなじ", meaning: "same" },
  お兄さん: { reading: "おにいさん", meaning: "(honorable) older brother" },
  お姉さん: { reading: "おねえさん", meaning: "(honorable) older sister" },
  "伯母さん/叔母さん": { reading: "おばさん", meaning: "Aunt" },
  お風呂: { reading: "おふろ", meaning: "Bath" },
  お弁当: { reading: "おべんとう", meaning: "boxed lunch" },
  覚える: { reading: "おぼえる", meaning: "to remember" },
  重い: { reading: "おもい", meaning: "Heavy" },
  泳ぐ: { reading: "およぐ", meaning: "to swim" },
  降りる: { reading: "おりる", meaning: "to get off, to descend" },
  終る: { reading: "おわる", meaning: "to finish" },
  音楽: { reading: "おんがく", meaning: "Music" },
  女: { reading: "おんな", meaning: "Woman" },
  女の子: { reading: "おんなのこ", meaning: "Girl" },
  外国: { reading: "がいこく", meaning: "foreign country" },
  外国人: { reading: "がいこくじん", meaning: "Foreigner" },
  会社: { reading: "かいしゃ", meaning: "Company" },
  階段: { reading: "かいだん", meaning: "Stairs" },
  買い物: { reading: "かいもの", meaning: "Shopping" },
  買う: { reading: "かう", meaning: "to buy" },
  返す: { reading: "かえす", meaning: "to return something" },
  帰る: { reading: "かえる", meaning: "to go back" },
  書く: { reading: "かく", meaning: "to write" },
  学生: { reading: "がくせい", meaning: "Student" },
  傘: { reading: "かさ", meaning: "Umbrella" },
  貸す: { reading: "かす", meaning: "to lend" },
  風: { reading: "かぜ", meaning: "Wind" },
  風邪: { reading: "かぜ", meaning: "a cold" },
  家族: { reading: "かぞく", meaning: "Family" },
  方: { reading: "かた", meaning: "person, way of doing" },
  学校: { reading: "がっこう", meaning: "School" },
  家庭: { reading: "かてい", meaning: "Household" },
  角: { reading: "かど", meaning: "a corner" },
  花瓶: { reading: "かびん", meaning: "a vase" },
  紙: { reading: "かみ", meaning: "paper" },
  火曜日: { reading: "かようび", meaning: "Tuesday" },
  辛い: { reading: "からい", meaning: "Spicy" },
  体: { reading: "からだ", meaning: "Body" },
  借りる: { reading: "かりる", meaning: "to borrow" },
  軽い: { reading: "かるい", meaning: "Light" },
  "川/河": { reading: "かわ", meaning: "River" },
  漢字: { reading: "かんじ", meaning: "Chinese character" },
  木: { reading: "き", meaning: "tree, wood" },
  黄色: { reading: "きいろ", meaning: "yellow" },
  黄色い: { reading: "きいろい", meaning: "yellow" },
  消える: { reading: "きえる", meaning: "to disappear" },
  聞く: { reading: "きく", meaning: "to hear, to listen to, to ask" },
  北: { reading: "きた", meaning: "North" },
  汚い: { reading: "きたない", meaning: "Dirty" },
  喫茶店: { reading: "きっさてん", meaning: "coffee lounge" },
  切手: { reading: "きって", meaning: "postage stamp" },
  切符: { reading: "きっぷ", meaning: "Ticket" },
  昨日: { reading: "きのう", meaning: "Yesterday" },
  九: { reading: "きゅう / く", meaning: "Nine" },
  牛肉: { reading: "ぎゅうにく", meaning: "Beef" },
  牛乳: { reading: "ぎゅうにゅう", meaning: "Milk" },
  今日: { reading: "きょう", meaning: "Today" },
  教室: { reading: "きょうしつ", meaning: "Classroom" },
  兄弟: { reading: "きょうだい", meaning: "(humble) siblings" },
  去年: { reading: "きょねん", meaning: "last year" },
  嫌い: { reading: "きらい", meaning: "Hate" },
  切る: { reading: "きる", meaning: "to cut" },
  着る: { reading: "きる", meaning: "to put on from the shoulders down" },
  銀行: { reading: "ぎんこう", meaning: "Bank" },
  金曜日: { reading: "きんようび", meaning: "Friday" },
  薬: { reading: "くすり", meaning: "medicine" },
  果物: { reading: "くだもの", meaning: "Fruit" },
  口: { reading: "くち", meaning: "mouth, opening" },
  靴: { reading: "くつ", meaning: "Shoes" },
  靴下: { reading: "くつした", meaning: "Socks" },
  国: { reading: "くに", meaning: "Country" },
  曇り: { reading: "くもり", meaning: "cloudy weather" },
  曇る: { reading: "くもる", meaning: "to become cloudy, to become dim" },
  暗い: { reading: "くらい", meaning: "Gloomy" },
  来る: { reading: "くる", meaning: "to come" },
  車: { reading: "くるま", meaning: "car, vehicle" },
  黒: { reading: "くろ", meaning: "Black" },
  黒い: { reading: "くろい", meaning: "black" },
  警官: { reading: "けいかん", meaning: "policeman" },
  今朝: { reading: "けさ", meaning: "this morning" },
  消す: { reading: "けす", meaning: "to erase, to turn off power" },
  結構: { reading: "けっこう", meaning: "splendid, enough" },
  結婚: { reading: "けっこん", meaning: "Marriage" },
  月曜日: { reading: "げつようび", meaning: "Monday" },
  玄関: { reading: "げんかん", meaning: "entry hall" },
  元気: { reading: "げんき", meaning: "health, vitality" },
  五: { reading: "ご", meaning: "Five" },
  公園: { reading: "こうえん", meaning: "Park" },
  交差点: { reading: "こうさてん", meaning: "intersection" },
  紅茶: { reading: "こうちゃ", meaning: "black tea" },
  交番: { reading: "こうばん", meaning: "police box" },
  声: { reading: "こえ", meaning: "Voice" },
  午後: { reading: "ごご", meaning: "afternoon" },
  九日: { reading: "ここのか", meaning: "nine days, ninth day" },
  九つ: { reading: "ここのつ", meaning: "Nine" },
  午前: { reading: "ごぜん", meaning: "morning" },
  答える: { reading: "こたえる", meaning: "to answer" },
  今年: { reading: "ことし", meaning: "this year" },
  言葉: { reading: "ことば", meaning: "word, language" },
  子供: { reading: "こども", meaning: "Child" },
  御飯: { reading: "ごはん", meaning: "cooked rice, meal" },
  困る: { reading: "こまる", meaning: "to be worried" },
  今月: { reading: "こんげつ", meaning: "this month" },
  今週: { reading: "こんしゅう", meaning: "this week" },
  今晩: { reading: "こんばん", meaning: "this evening" },
  財布: { reading: "さいふ", meaning: "Wallet" },
  魚: { reading: "さかな", meaning: "Fish" },
  先: { reading: "さき", meaning: "the future, previous" },
  咲く: { reading: "さく", meaning: "to bloom" },
  作文: { reading: "さくぶん", meaning: "composition, writing" },
  差す: {
    reading: "さす",
    meaning: "to stretch out hands, to raise an umbrella",
  },
  雑誌: { reading: "ざっし", meaning: "Magazine" },
  砂糖: { reading: "さとう", meaning: "Sugar" },
  寒い: { reading: "さむい", meaning: "Cold" },
  さ来年: { reading: "さらいねん", meaning: "year after next" },
  三: { reading: "さん", meaning: "Three" },
  散歩: { reading: "さんぽする", meaning: "to stroll" },
  四: { reading: "し / よん", meaning: "Four" },
  塩: { reading: "しお", meaning: "Salt" },
  時間: { reading: "じかん", meaning: "Time" },
  仕事: { reading: "しごと", meaning: "Job" },
  辞書: { reading: "じしょ", meaning: "Dictionary" },
  静か: { reading: "しずか", meaning: "Quiet" },
  下: { reading: "した", meaning: "Below" },
  七: { reading: "しち / なな", meaning: "Seven" },
  質問: { reading: "しつもん", meaning: "Question" },
  自転車: { reading: "じてんしゃ", meaning: "Bicycle" },
  自動車: { reading: "じどうしゃ", meaning: "Automobile" },
  死ぬ: { reading: "しぬ", meaning: "to die" },
  字引: { reading: "じびき", meaning: "Dictionary" },
  自分: { reading: "じぶん", meaning: "Oneself" },
  閉まる: { reading: "しまる", meaning: "to close, to be closed" },
  閉める: { reading: "しめる", meaning: "to close something" },
  締める: { reading: "しめる", meaning: "to tie" },
  写真: { reading: "しゃしん", meaning: "photograph" },
  十: { reading: "じゅう とお", meaning: "Ten" },
  授業: { reading: "じゅぎょう", meaning: "lesson, class work" },
  宿題: { reading: "しゅくだい", meaning: "homework" },
  上手: { reading: "じょうず", meaning: "Skillful" },
  丈夫: { reading: "じょうぶ", meaning: "strong, durable" },
  食堂: { reading: "しょくどう", meaning: "dining hall" },
  知る: { reading: "しる", meaning: "to know" },
  白: { reading: "しろ", meaning: "White" },
  白い: { reading: "しろい", meaning: "White" },
  新聞: { reading: "しんぶん", meaning: "newspaper" },
  水曜日: { reading: "すいようび", meaning: "Wednesday" },
  吸う: { reading: "すう", meaning: "to smoke, to suck" },
  好き: { reading: "すき", meaning: "Likeable" },
  少ない: { reading: "すくない", meaning: "a few" },
  少し: { reading: "すこし", meaning: "Few" },
  涼しい: { reading: "すずしい", meaning: "Refreshing" },
  住む: { reading: "すむ", meaning: "to live in" },
  座る: { reading: "すわる", meaning: "to sit" },
  背: { reading: "せ", meaning: "height, stature" },
  生徒: { reading: "せいと", meaning: "Pupil" },
  背広: { reading: "せびろ", meaning: "business suit" },
  狭い: { reading: "せまい", meaning: "Narrow" },
  千: { reading: "せん", meaning: "Thousand" },
  先月: { reading: "せんげつ", meaning: "last month" },
  先週: { reading: "せんしゅう", meaning: "last week" },
  先生: { reading: "せんせい", meaning: "teacher, doctor" },
  洗濯: { reading: "せんたく", meaning: "Washing" },
  全部: { reading: "ぜんぶ", meaning: "All" },
  掃除: { reading: "そうじする", meaning: "to clean, to sweep" },
  外: { reading: "そと", meaning: "Outside" },
  空: { reading: "そら", meaning: "Sky" },
  大学: { reading: "だいがく", meaning: "university" },
  大使館: { reading: "たいしかん", meaning: "embassy" },
  大丈夫: { reading: "だいじょうぶ", meaning: "all right" },
  大好き: { reading: "だいすき", meaning: "to be very likeable" },
  大切: { reading: "たいせつ", meaning: "important" },
  台所: { reading: "だいどころ", meaning: "kitchen" },
  高い: { reading: "たかい", meaning: "tall, expensive" },
  出す: { reading: "だす", meaning: "to put out" },
  立つ: { reading: "たつ", meaning: "to stand" },
  建物: { reading: "たてもの", meaning: "building" },
  楽しい: { reading: "たのしい", meaning: "enjoyable" },
  頼む: { reading: "たのむ", meaning: "to ask" },
  食べ物: { reading: "たべもの", meaning: "food" },
  食べる: { reading: "たべる", meaning: "to eat" },
  卵: { reading: "たまご", meaning: "egg" },
  誰: { reading: "だれ", meaning: "who" },
  誰: { reading: "だれか", meaning: "somebody" },
  誕生日: { reading: "たんじょうび", meaning: "birthday" },
  小さい: { reading: "ちいさい", meaning: "little" },
  小さな: { reading: "ちいさな", meaning: "little" },
  近い: { reading: "ちかい", meaning: "near" },
  違う: { reading: "ちがう", meaning: "to differ" },
  近く: { reading: "ちかく", meaning: "near" },
  地下鉄: { reading: "ちかてつ", meaning: "underground train" },
  地図: { reading: "ちず", meaning: "map" },
  茶色: { reading: "ちゃいろ", meaning: "brown" },
  一日: { reading: "ついたち", meaning: "first of month" },
  使う: { reading: "つかう", meaning: "to use" },
  疲れる: { reading: "つかれる", meaning: "to get tired" },
  次: { reading: "つぎ", meaning: "next" },
  着く: { reading: "つく", meaning: "to arrive at" },
  机: { reading: "つくえ", meaning: "desk" },
  作る: { reading: "つくる", meaning: "to make" },
  勤める: { reading: "つとめる", meaning: "to work for someone" },
  冷たい: { reading: "つめたい", meaning: "cold to the touch" },
  強い: { reading: "つよい", meaning: "powerful" },
  手: { reading: "て", meaning: "hand" },
  出かける: { reading: "でかける", meaning: "to go out" },
  手紙: { reading: "てがみ", meaning: "letter" },
  出口: { reading: "でぐち", meaning: "exit" },
  出る: { reading: "でる", meaning: "to appear, to leave" },
  天気: { reading: "てんき", meaning: "weather" },
  電気: { reading: "でんき", meaning: "electricity, electric light" },
  電車: { reading: "でんしゃ", meaning: "electric train" },
  電話: { reading: "でんわ", meaning: "telephone" },
  戸: { reading: "と", meaning: "Japanese style door" },
  動物: { reading: "どうぶつ", meaning: "animal" },
  遠い: { reading: "とおい", meaning: "far" },
  十日: { reading: "とおか", meaning: "ten days, the tenth day" },
  時々: { reading: "ときどき", meaning: "sometimes" },
  時計: { reading: "とけい", meaning: "watch, clock" },
  所: { reading: "ところ", meaning: "place" },
  年: { reading: "とし", meaning: "year" },
  図書館: { reading: "としょかん", meaning: "library" },
  隣: { reading: "となり", meaning: "next door to" },
  飛ぶ: { reading: "とぶ", meaning: "to fly, to hop" },
  止まる: { reading: "とまる", meaning: "to come to a halt" },
  友達: { reading: "ともだち", meaning: "friend" },
  土曜日: { reading: "どようび", meaning: "Saturday" },
  鳥: { reading: "とり", meaning: "bird" },
  とり肉: { reading: "とりにく", meaning: "chicken meat" },
  取る: { reading: "とる", meaning: "to take something" },
  撮る: { reading: "とる", meaning: "to take a photo or record a film" },
  中: { reading: "なか", meaning: "middle" },
  長い: { reading: "ながい", meaning: "long" },
  鳴く: {
    reading: "なく",
    meaning: "animal noise. to chirp, roar or croak etc.",
  },
  無くす: { reading: "なくす", meaning: "to lose something" },
  夏: { reading: "なつ", meaning: "summer" },
  夏休み: { reading: "なつやすみ", meaning: "summer holiday" },
  七つ: { reading: "ななつ", meaning: "seven" },
  七日: { reading: "なのか", meaning: "seven days, the seventh day" },
  名前: { reading: "なまえ", meaning: "name" },
  習う: { reading: "ならう", meaning: "to learn" },
  並ぶ: { reading: "ならぶ", meaning: "to line up, to stand in a line" },
  並べる: { reading: "ならべる", meaning: "to line up, to set up" },
  何: { reading: "なん/なに", meaning: "what" },
  二: { reading: "に", meaning: "two" },
  賑やか: { reading: "にぎやか", meaning: "bustling, busy" },
  肉: { reading: "にく", meaning: "meat" },
  西: { reading: "にし", meaning: "west" },
  日曜日: { reading: "にちようび", meaning: "Sunday" },
  荷物: { reading: "にもつ", meaning: "luggage" },
  庭: { reading: "にわ", meaning: "garden" },
  脱ぐ: { reading: "ぬぐ", meaning: "to take off clothes" },
  温い: { reading: "ぬるい", meaning: "luke warm" },
  猫: { reading: "ねこ", meaning: "cat" },
  寝る: { reading: "ねる", meaning: "to go to bed, to sleep" },
  登る: { reading: "のぼる", meaning: "to climb" },
  飲み物: { reading: "のみもの", meaning: "a drink" },
  飲む: { reading: "のむ", meaning: "to drink" },
  乗る: { reading: "のる", meaning: "to get on, to ride" },
  歯: { reading: "は", meaning: "tooth" },
  灰皿: { reading: "はいざら", meaning: "ashtray" },
  入る: { reading: "はいる", meaning: "to enter, to contain" },
  葉書: { reading: "はがき", meaning: "postcard" },
  箱: { reading: "はこ", meaning: "box" },
  橋: { reading: "はし", meaning: "bridge" },
  始まる: { reading: "はじまる", meaning: "to begin" },
  "初め/始め": { reading: "はじめ", meaning: "beginning" },
  初めて: { reading: "はじめて", meaning: "for the first time" },
  走る: { reading: "はしる", meaning: "to run" },
  二十歳: { reading: "はたち", meaning: "20 years old,20th year" },
  働く: { reading: "はたらく", meaning: "to work" },
  八: { reading: "はち", meaning: "eight" },
  二十日: { reading: "はつか", meaning: "twenty days, twentieth" },
  花: { reading: "はな", meaning: "flower" },
  鼻: { reading: "はな", meaning: "nose" },
  話: { reading: "はなし", meaning: "talk, story" },
  話す: { reading: "はなす", meaning: "to speak" },
  早い: { reading: "はやい", meaning: "early" },
  速い: { reading: "はやい", meaning: "quick" },
  春: { reading: "はる", meaning: "spring" },
  貼る: { reading: "はる", meaning: "to stick" },
  晴れ: { reading: "はれ", meaning: "clear weather" },
  晴れる: { reading: "はれる", meaning: "to be sunny" },
  半: { reading: "はん", meaning: "half" },
  晩: { reading: "ばん", meaning: "evening" },
  番号: { reading: "ばんごう", meaning: "number" },
  晩御飯: { reading: "ばんごはん", meaning: "evening meal" },
  半分: { reading: "はんぶん", meaning: "half minute" },
  東: { reading: "ひがし", meaning: "east" },
  引く: { reading: "ひく", meaning: "to pull" },
  弾く: {
    reading: "ひく",
    meaning: "to play an instrument with strings, including piano",
  },
  低い: { reading: "ひくい", meaning: "short, low" },
  飛行機: { reading: "ひこうき", meaning: "aeroplane" },
  左: { reading: "ひだり", meaning: "left hand side" },
  人: { reading: "ひと", meaning: "person" },
  一つ: { reading: "ひとつ", meaning: "one" },
  一月: { reading: "ひとつき", meaning: "one month" },
  一人: { reading: "ひとり", meaning: "one person" },
  暇: { reading: "ひま", meaning: "free time" },
  百: { reading: "ひゃく", meaning: "hundred" },
  病院: { reading: "びょういん", meaning: "hospital" },
  病気: { reading: "びょうき", meaning: "illness" },
  昼: { reading: "ひる", meaning: "noon, daytime" },
  昼御飯: { reading: "ひるごはん", meaning: "midday meal" },
  広い: { reading: "ひろい", meaning: "spacious, wide" },
  封筒: { reading: "ふうとう", meaning: "envelope" },
  吹く: { reading: "ふく", meaning: "to blow" },
  服: { reading: "ふく", meaning: "clothes" },
  二つ: { reading: "ふたつ", meaning: "two" },
  豚肉: { reading: "ぶたにく", meaning: "pork" },
  二人: { reading: "ふたり", meaning: "two people" },
  二日: { reading: "ふつか", meaning: "two days, second day of the month" },
  太い: { reading: "ふとい", meaning: "fat" },
  冬: { reading: "ふゆ", meaning: "winter" },
  降る: { reading: "ふる", meaning: "to fall, e.g. rain or snow" },
  古い: { reading: "ふるい", meaning: "old (not used for people)" },
  文章: { reading: "ぶんしょう", meaning: "sentence, text" },
  下手: { reading: "へた", meaning: "unskillful" },
  部屋: { reading: "へや", meaning: "room" },
  辺: { reading: "へん", meaning: "area" },
  勉強: { reading: "べんきょうする", meaning: "to study" },
  便利: { reading: "べんり", meaning: "useful, convenient" },
  帽子: { reading: "ぼうし", meaning: "hat" },
  欲しい: { reading: "ほしい", meaning: "want" },
  細い: { reading: "ほそい", meaning: "thin" },
  本: { reading: "ほん", meaning: "book" },
  本棚: { reading: "ほんだな", meaning: "bookshelves" },
  毎朝: { reading: "まいあさ", meaning: "every morning" },
  毎月: { reading: "まいげつ/まいつき", meaning: "every month" },
  毎週: { reading: "まいしゅう", meaning: "every week" },
  毎日: { reading: "まいにち", meaning: "every day" },
  毎年: { reading: "まいねん/まいとし", meaning: "every year" },
  毎晩: { reading: "まいばん", meaning: "every night" },
  前: { reading: "まえ", meaning: "before" },
  曲る: { reading: "まがる", meaning: "to turn, to bend" },
  町: { reading: "まち", meaning: "town, city" },
  待つ: { reading: "まつ", meaning: "to wait" },
  窓: { reading: "まど", meaning: "window" },
  "丸い/円い": { reading: "まるい", meaning: "round, circular" },
  万: { reading: "まん", meaning: "ten thousand" },
  万年筆: { reading: "まんねんひつ", meaning: "fountain pen" },
  磨く: { reading: "みがく", meaning: "to brush teeth, to polish" },
  右: { reading: "みぎ", meaning: "right side" },
  短い: { reading: "みじかい", meaning: "short" },
  水: { reading: "みず", meaning: "water" },
  店: { reading: "みせ", meaning: "shop" },
  見せる: { reading: "みせる", meaning: "to show" },
  道: { reading: "みち", meaning: "street" },
  三日: { reading: "みっか", meaning: "three days, third day of the month" },
  三つ: { reading: "みっつ", meaning: "three" },
  緑: { reading: "みどり", meaning: "green" },
  皆さん: { reading: "みなさん", meaning: "everyone" },
  南: { reading: "みなみ", meaning: "south" },
  耳: { reading: "みみ", meaning: "ear" },
  "見る 観る": { reading: "みる", meaning: "to see, to watch" },
  六日: { reading: "むいか", meaning: "six days, sixth day of the month" },
  向こう: { reading: "むこう", meaning: "over there" },
  難しい: { reading: "むずかしい", meaning: "difficult" },
  六つ: { reading: "むっつ", meaning: "six" },
  村: { reading: "むら", meaning: "village" },
  目: { reading: "め", meaning: "eye" },
  眼鏡: { reading: "めがね", meaning: "glasses" },
  もう一度: { reading: "もういちど", meaning: "again" },
  木曜日: { reading: "もくようび", meaning: "Thursday" },
  持つ: { reading: "もつ", meaning: "to hold" },
  物: { reading: "もの", meaning: "thing" },
  門: { reading: "もん", meaning: "gate" },
  問題: { reading: "もんだい", meaning: "problem" },
  八百屋: { reading: "やおや", meaning: "greengrocer" },
  野菜: { reading: "やさい", meaning: "vegetable" },
  易しい: { reading: "やさしい", meaning: "easy, simple" },
  安い: { reading: "やすい", meaning: "cheap" },
  休み: { reading: "やすみ", meaning: "rest, holiday" },
  休む: { reading: "やすむ", meaning: "to rest" },
  八つ: { reading: "やっつ", meaning: "eight" },
  山: { reading: "やま", meaning: "mountain" },
  夕方: { reading: "ゆうがた", meaning: "evening" },
  夕飯: { reading: "ゆうはん", meaning: "dinner" },
  郵便局: { reading: "ゆうびんきょく", meaning: "post office" },
  昨夜: { reading: "ゆうべ", meaning: "last night" },
  有名: { reading: "ゆうめい", meaning: "famous" },
  雪: { reading: "ゆき", meaning: "snow" },
  行く: { reading: "ゆく", meaning: "to go" },
  八日: { reading: "ようか", meaning: "eight days, eighth day of the month" },
  洋服: { reading: "ようふく", meaning: "western-style clothes" },
  横: { reading: "よこ", meaning: "beside, side, width" },
  四日: { reading: "よっか", meaning: "four days, fouth day of the month" },
  四つ: { reading: "よっつ", meaning: "four" },
  呼ぶ: { reading: "よぶ", meaning: "to call out, to invite" },
  読む: { reading: "よむ", meaning: "to read" },
  夜: { reading: "よる", meaning: "evening, night" },
  弱い: { reading: "よわい", meaning: "weak" },
  来月: { reading: "らいげつ", meaning: "next month" },
  来週: { reading: "らいしゅう", meaning: "next week" },
  来年: { reading: "らいねん", meaning: "next year" },
  留学生: { reading: "りゅうがくせい", meaning: "overseas student" },
  両親: { reading: "りょうしん", meaning: "both parents" },
  料理: { reading: "りょうり", meaning: "cuisine" },
  旅行: { reading: "りょこう", meaning: "travel" },
  零: { reading: "れい", meaning: "zero" },
  冷蔵庫: { reading: "れいぞうこ", meaning: "refrigerator" },
  練習: { reading: "れんしゅうする", meaning: "to practice" },
  廊下: { reading: "ろうか", meaning: "corridor" },
  六: { reading: "ろく", meaning: "six" },
  若い: { reading: "わかい", meaning: "young" },
  分かる: { reading: "わかる", meaning: "to be understood" },
  忘れる: { reading: "わすれる", meaning: "to forget" },
  私: { reading: "わたくし", meaning: "(humble) I, myself" },
  私: { reading: "わたし", meaning: "I, myself" },
  渡す: { reading: "わたす", meaning: "to hand over" },
  渡る: { reading: "わたる", meaning: "to go across" },
  悪い: { reading: "わるい", meaning: "bad" },
};
